#!/bin/sh
set -eu
self=$0
while [ -L "$self" ]; do
  dir=$(CDPATH= cd -- "$(dirname -- "$self")" && pwd)
  target=$(readlink "$self")
  case $target in
    /*) self=$target ;;
    *) self=$dir/$target ;;
  esac
done
root=$(CDPATH= cd -- "$(dirname -- "$self")/../.." && pwd)
exec node "$root/bin/codex-meter.js" "$@"
