const app=document.querySelector('#app');const toast=document.querySelector('#toast');let csrf=null;let range='today';let pollTimer=null;let cycleAccountId=null;let cycleWindowKey=null;
class DisplayError extends Error{}const errorCopy=error=>error instanceof DisplayError?error.message:'Unexpected Server response.';
const el=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key==='text')node.textContent=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==null&&value!==false)node.setAttribute(key,value===true?'':String(value));}for(const child of children.flat()){if(child!==null&&child!==undefined)node.append(child instanceof Node?child:document.createTextNode(String(child)));}return node;};
function clear(node=app){node.replaceChildren();}function notify(message){toast.textContent=message;toast.hidden=false;setTimeout(()=>{toast.hidden=true;},3500);}function fmt(value){try{return BigInt(value).toLocaleString();}catch{return '—';}}function when(value){return value?new Date(value).toLocaleString():'Never';}
async function api(path,options={}){const init={credentials:'same-origin',headers:{accept:'application/json'},...options};if(options.body!==undefined){init.headers={...init.headers,'content-type':'application/json','x-csrf-token':csrf};init.body=JSON.stringify(options.body);}let response;try{response=await fetch(`/api/v1${path}`,init);}catch{throw new DisplayError('The Server could not be reached.');}let data={};try{data=await response.json();}catch{}if(response.status===401){csrf=null;renderLogin();throw new DisplayError('Your session expired.');}if(!response.ok){const copies={invalid_account:'Select an active Account Profile.',invalid_mode:'Select how this Codex login is used.',binding_exists_or_mode_conflict:'That Account Profile is already tracked here, or this login option is already in use.',binding_identity_conflict:'The existing local assignment could not be resumed.',enrollment_expired:'This enrollment expired. Create a new device enrollment.'};throw new DisplayError(copies[data.error]??'The request could not be completed.');}return data;}
const STATUS_LABELS={waiting_for_agent:'Waiting for Agent',applying:'Applying',tracking:'Tracking',login_required:'Login required',quota_unavailable:'Quota unavailable',agent_offline:'Agent offline',apply_failed:'Apply failed',stop_tracking_pending:'Stopping',stopped:'Not tracking',online:'Online',offline:'Offline',stale:'Stale',disabled:'Disabled',available:'Available',unavailable:'Unavailable',ambiguous:'Ambiguous',reporter_offline:'Reporter offline',collection_failed:'Collection failed',stale_observation:'Observation stale',no_reporter:'No reporter'};
function status(value){const raw=String(value??'unknown'),label=STATUS_LABELS[raw]??raw.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase());return el('span',{class:`status ${raw}`,text:label});}function heading(title,subtitle,actions=[]){return el('div',{class:'toolbar'},el('div',{},el('h1',{text:title}),el('div',{class:'subtitle',text:subtitle})),el('div',{class:'actions'},actions));}
function list(value,key){if(!value||!Array.isArray(value[key]))throw new DisplayError('Unexpected Server response.');return value[key];}
function environmentLabel(mode){return mode==='default'?"Using this device's current Codex login":mode==='isolated'?'Separate Codex login':'Existing Codex login';}
function coverageCopy(coverage){if(!coverage||!Number.isSafeInteger(coverage.registeredDevices)||!Number.isSafeInteger(coverage.reportingDevices))return'Coverage unavailable';const devices=`${coverage.reportingDevices} / ${coverage.registeredDevices} registered device${coverage.registeredDevices===1?'':'s'} reporting`;return coverage.status==='full'?devices:`${devices} - estimate may be incomplete`;}
function loginCommand(profile){if(profile.trackingState!=='login_required')return null;if(profile.actual?.launcher)return`${profile.actual.launcher} login`;return profile.mode==='default'?'codex login':null;}
function environmentChoices({currentAvailable=true,testId='environment'}={}){const current=el('input',{type:'radio',name:testId,value:'default','data-testid':`${testId}-current`}),separate=el('input',{type:'radio',name:testId,value:'isolated','data-testid':`${testId}-separate`});current.disabled=!currentAvailable;current.checked=currentAvailable;separate.checked=!currentAvailable;const field=el('fieldset',{class:'choice-group'},el('legend',{text:'How do you use this account?'}),el('label',{class:`choice-option${currentAvailable?'':' disabled'}`},current,el('span',{},el('strong',{text:"Use this device's current Codex login"}),currentAvailable?null:el('small',{text:'The current login is already assigned.'}))),el('label',{class:'choice-option'},separate,el('span',{},el('strong',{text:'Add another Codex login'}))));return{field,value:()=>current.checked?'default':'isolated'};}
function shell(content,current){clear();const links=[['overview','Overview'],['groups','Groups'],['devices','Devices'],['accounts','Accounts'],['settings','Settings']];const nav=el('nav',{class:'nav','aria-label':'Main navigation'},...links.map(([id,label])=>el('a',{href:`#/${id}`,'aria-current':current===id?'page':null,text:label})));const logout=el('button',{class:'logout',text:'Log out',onclick:async()=>{try{await api('/auth/logout',{method:'POST',body:{}});}finally{csrf=null;renderLogin();}}});app.append(el('div',{class:'shell'},el('aside',{class:'sidebar'},el('div',{class:'brand'},'Codex Meter',el('small',{text:'Measured usage dashboard'})),nav,logout),el('main',{class:'main',id:'main'},content)));}
function renderLogin(message=''){clear();const password=el('input',{type:'password',name:'password',autocomplete:'current-password',required:true,minlength:'12'});const error=el('p',{class:'error',text:message});const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();error.textContent='';const button=form.querySelector('button');button.disabled=true;try{const result=await api('/auth/login',{method:'POST',body:{password:password.value}});csrf=result.csrfToken;location.hash='#/overview';await route();}catch(e){error.textContent=errorCopy(e);}finally{button.disabled=false;}}},el('label',{},'Administrator password',password),error,el('button',{class:'primary',type:'submit',text:'Sign in'}));app.append(el('main',{class:'login',id:'main'},el('section',{class:'card','aria-labelledby':'login-title'},el('h1',{id:'login-title',text:'Codex Meter'}),el('p',{class:'muted',text:'Sign in to administer measured usage.'}),form)));password.focus();}
function rangeTabs(onchange){return el('div',{class:'tabs','aria-label':'Usage range'},...[['today','Today'],['7d','7D'],['30d','30D'],['all','All']].map(([value,label])=>el('button',{type:'button','aria-pressed':range===value,text:label,onclick:()=>{range=value;onchange();}})));}
function quotaCard(quota){const card=el('section',{class:'card quota','aria-labelledby':'quota-title'},el('div',{class:'toolbar'},el('div',{},el('h2',{id:'quota-title',text:'Account Quota'}),el('div',{class:'muted',text:quota.planType?`${quota.planType} plan`:'Provider quota status'})),status(quota.status)));if(quota.reporterState!=='available'){const copies={no_reporter:'No quota reporter is configured for this profile.',reporter_offline:'The quota reporter is offline.',collection_failed:`The reporter is online, but quota collection failed${quota.errorKind?` (${quota.errorKind.replaceAll('_',' ')})`:''}.`,stale_observation:`The last quota observation is stale. Last observed ${when(quota.observedAt)}.`};const copy=copies[quota.reporterState]??(quota.status==='ambiguous'?'Quota windows are ambiguous; no current value was selected.':'Quota is unavailable.');card.append(el('div',{class:'notice',text:copy}));}if(quota.windows?.length){card.append(el('div',{class:'quota-grid'},...quota.windows.map(window=>el('div',{class:'quota-window'},el('div',{class:'metric-label',text:`${window.limitId} · ${window.durationMinutes} min`}),el('div',{class:'big',text:`${window.usedPercent}% used`}),el('progress',{class:'meter',max:'100',value:String(Math.max(0,Math.min(100,window.usedPercent))),'aria-label':`${window.usedPercent}% used`}),el('div',{class:'muted',text:window.resetsAt?`Resets ${when(window.resetsAt)}`:'Reset time unavailable'})))));}return card;}
function quotaWindowKey(window){return `${window.limitId}\u0000${window.durationMinutes}`;}
function quotaWindowLabel(window){if(window.durationMinutes===300)return'5H';if(window.durationMinutes===10080)return'Weekly';const minutes=window.durationMinutes;return minutes%1440===0?`${minutes/1440}D`:minutes%60===0?`${minutes/60}H`:`${minutes} min`;}
function resetDistance(value){if(!value)return'Reset time unavailable';const milliseconds=Date.parse(value)-Date.now();if(milliseconds<=0)return'Reset boundary passed';const minutes=Math.ceil(milliseconds/60000),days=Math.floor(minutes/1440),hours=Math.floor((minutes%1440)/60),rest=minutes%60;return`Resets in ${days?`${days}d `:''}${hours?`${hours}h `:''}${rest}m`;}
function cycleView(accountsData,attribution){
  const activeAccounts=accountsData.accounts.filter(account=>!account.archivedAt),account=activeAccounts.find(item=>item.id===attribution.accountId);
  const accountSelect=el('select',{'aria-label':'Account Profile'},...activeAccounts.map(item=>el('option',{value:item.id,text:item.name})));
  accountSelect.value=attribution.accountId;accountSelect.addEventListener('change',()=>{cycleAccountId=accountSelect.value;cycleWindowKey=null;overview();});
  const controls=activeAccounts.length>1?el('label',{class:'inline-control'},el('span',{class:'metric-label',text:'Account'}),accountSelect):el('div',{class:'metric-label',text:`Account: ${account?.name??'Profile'}`});
  const section=el('section',{class:'provider-cycle','aria-labelledby':'cycle-heading'},el('div',{class:'toolbar'},el('div',{},el('h2',{id:'cycle-heading',text:'Provider cycle view'}),el('div',{class:'muted',text:'Current provider-defined quota cycle'})),controls));
  const reporterCopies={no_reporter:'No quota reporter is configured for this Account Profile.',reporter_offline:`The quota reporter is offline. Last observed ${when(attribution.quota.observedAt)}.`,collection_failed:`Quota collection failed${attribution.quota.errorKind?` (${attribution.quota.errorKind.replaceAll('_',' ')})`:''}.`,stale_observation:`The last quota observation is stale. Last observed ${when(attribution.quota.observedAt)}.`};
  const reporterNotice=attribution.quota.reporterState==='available'?null:el('div',{class:'notice',text:reporterCopies[attribution.quota.reporterState]??'Quota reporter state is unavailable.'});
  const badge=attribution.quota.reporterState==='available'?attribution.quota.status:attribution.quota.reporterState;
  if(!attribution.windows.length){section.append(el('div',{class:'card'},el('div',{class:'toolbar'},el('h2',{text:'Cycle attribution unavailable'}),status(badge)),reporterNotice,el('p',{class:'muted',text:'A valid provider reset boundary and quota observation are required.'}),el('div',{class:'notice',text:'Estimated from tracked token usage. This is not provider-attributed usage.'})));return section;}
  if(!attribution.windows.some(window=>quotaWindowKey(window)===cycleWindowKey))cycleWindowKey=quotaWindowKey(attribution.windows[0]);
  const window=attribution.windows.find(item=>quotaWindowKey(item)===cycleWindowKey);
  const tabs=el('div',{class:'tabs','aria-label':'Provider quota window'},...attribution.windows.map(item=>{const key=quotaWindowKey(item);return el('button',{type:'button','aria-pressed':key===cycleWindowKey,text:quotaWindowLabel(item),onclick:()=>{cycleWindowKey=key;overview();}});}));
  const cycleCoverage=window.coverage.status==='full'?'Full cycle':window.coverage.status==='partial'?`Partial - tracking began ${when(window.coverage.from)}`:'Cycle boundary unavailable';
  const trackingCoverage=coverageCopy(account?.trackingCoverage);
  const quotaValue=window.usedPercent===null?'Unavailable':`${window.usedPercent}% used`;
  const staleNotice=window.estimate.status==='stale'&&attribution.quota.reporterState!=='stale_observation'?el('div',{class:'notice',text:`Estimated from stale quota snapshot observed ${when(window.estimate.basedOnObservedAt)}.`}):null;
  const coverageNotice=account?.trackingCoverage?.status!=='full'?el('div',{class:'notice',text:'One or more registered devices are not reporting. The estimate may be incomplete.'}):null;
  const summary=el('section',{class:'card cycle-summary'},el('div',{class:'toolbar'},el('div',{},el('h2',{text:`Current ${quotaWindowLabel(window)} Cycle`}),el('div',{class:'muted',text:account?.name??'Account Profile'})),status(badge)),reporterNotice,el('div',{class:'metric-grid'},el('div',{},el('div',{class:'metric-label',text:'Provider usage'}),el('div',{class:'big',text:quotaValue})),el('div',{},el('div',{class:'metric-label',text:'Tracking coverage'}),el('div',{class:'big compact',text:trackingCoverage})),el('div',{},el('div',{class:'metric-label',text:'Cycle coverage'}),el('div',{class:'big compact',text:cycleCoverage})),el('div',{},el('div',{class:'metric-label',text:'Reset'}),el('div',{class:'big compact',text:resetDistance(window.resetsAt)}))),coverageNotice,staleNotice);
  const cards=window.groups.map(entry=>{const contribution=entry.estimatedQuotaContributionPercentagePoints;const estimateText=contribution===null?'Unavailable':`~${contribution.toFixed(1)}%p`;const estimateLabel=window.coverage.status==='partial'?'Estimated quota contribution since tracking began':'Estimated quota contribution';return el('article',{class:'card'},el('h2',{text:entry.label}),el('div',{class:'big',text:fmt(entry.trackedTokens)}),el('div',{class:'muted',text:window.coverage.status==='partial'?'tracked since coverage began':'tracked tokens this cycle'}),el('div',{class:'metric-label',text:'Share of tracked usage'}),el('div',{class:'big',text:entry.trackedSharePercent===null?'—':`${entry.trackedSharePercent.toFixed(2)}%`}),el('div',{class:'metric-label',text:estimateLabel}),el('div',{class:'big',text:estimateText}));});
  section.append(tabs,summary,el('div',{class:'grid'},...cards),el('div',{class:'notice',text:'Estimated by allocating provider-reported account usage in proportion to locally tracked token usage. This is not provider-attributed usage. Untracked devices or usage may make this estimate inaccurate.'}));return section;
}
function historicalView(summary){return el('section',{'aria-labelledby':'historical-heading'},el('div',{class:'toolbar'},el('div',{},el('h2',{id:'historical-heading',text:'Historical tracked usage'}),el('div',{class:'muted',text:'Measured usage ranges; not provider quota attribution'})),rangeTabs(overview)),el('div',{class:'grid'},...summary.groups.map(entry=>{const name=entry.group?.name??'Unassigned';return el('a',{class:'card card-link',href:entry.group?`#/groups/${encodeURIComponent(entry.group.id)}`:'#/groups'},el('h2',{text:name}),el('div',{class:'big',text:fmt(entry.combined.totalTokens)}),el('div',{class:'muted',text:'combined tokens'}),el('div',{class:'metric-label',text:'Share of measured token usage'}),el('div',{class:'big',text:`${entry.shares.measured.toFixed(2)}%`}),el('div',{class:'muted',text:`Measured ${fmt(entry.measured.totalTokens)} · Adjustments ${fmt(entry.adjusted.totalTokens)}`}));})));
}
async function overview(){const root=el('div',{},heading('Overview','Provider-cycle estimates and historical measured usage'));shell(root,'overview');try{const accountsData=await api('/accounts?range=all');const active=list(accountsData,'accounts').filter(account=>!account.archivedAt);if(!active.some(account=>account.id===cycleAccountId))cycleAccountId=(active.find(account=>account.reference)??active[0])?.id??null;const requests=[api(`/usage/summary?range=${range}`)];if(cycleAccountId)requests.push(api(`/accounts/${encodeURIComponent(cycleAccountId)}/quota-attribution`));const[summary,attribution]=await Promise.all(requests);if(attribution)root.append(cycleView(accountsData,attribution));else root.append(el('div',{class:'notice',text:'Create and bind an Account Profile to enable provider-cycle attribution.'}));root.append(historicalView(summary));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
function adjustmentForm(scope,onDone){const amount=el('input',{required:true,inputmode:'numeric',placeholder:'e.g. 100 or -50'}),reason=el('textarea',{required:true,maxlength:'500',placeholder:'Reason (required)'});return el('form',{class:'form',onsubmit:async event=>{event.preventDefault();try{await api('/usage/adjustments',{method:'POST',body:{...scope,amountTokens:amount.value,reason:reason.value,occurredAt:new Date().toISOString()}});notify('Adjustment recorded');onDone();}catch(e){notify(errorCopy(e));}}},el('h2',{text:'Manual adjustment'}),el('p',{class:'muted',text:'Adjustments remain separate from measured usage.'}),el('label',{},'Token amount',amount),el('label',{},'Reason',reason),el('button',{class:'primary',type:'submit',text:'Record adjustment'}));}
function usageDetails(data){const dims=[['inputTokens','Input'],['cachedInputTokens','Cached input'],['cacheWriteInputTokens','Cache-write input'],['outputTokens','Output'],['reasoningOutputTokens','Reasoning output'],['totalTokens','Total']];return el('section',{class:'card'},el('div',{class:'split'},...[[data.measured.totalTokens,'Measured'],[data.adjusted.totalTokens,'Adjustments'],[data.combined.totalTokens,'Combined']].map(([v,n])=>el('div',{},el('div',{class:'metric-label',text:n}),el('div',{class:'big',text:fmt(v)})))),el('h2',{text:'Measured token dimensions'}),el('div',{class:'dimensions'},...dims.map(([key,label])=>el('div',{class:'dimension'},el('span',{class:'muted',text:label}),el('strong',{text:fmt(data.measured[key])})))));}
async function groups(){const root=el('div');const add=el('button',{class:'primary',text:'New group',onclick:()=>groupDialog(null,groups)});root.append(heading('Groups','Organize device attribution',[add]));shell(root,'groups');try{const data=await api('/groups'),groupRows=list(data,'groups');const active=groupRows.filter(g=>!g.archivedAt),archived=groupRows.filter(g=>g.archivedAt);root.append(el('div',{class:'list'},...(active.length?active.map(g=>el('div',{class:'list-row'},el('a',{href:`#/groups/${encodeURIComponent(g.id)}`,text:g.name}),el('button',{text:'Rename',onclick:()=>groupDialog(g,groups)}))):[el('div',{class:'empty',text:'No active groups.'})])));if(archived.length)root.append(el('section',{class:'card'},el('h2',{text:'Archived'}),...archived.map(g=>el('div',{class:'muted',text:g.name}))));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
function groupDialog(group,onDone){const dialog=el('dialog'),input=el('input',{required:true,maxlength:'200',value:group?.name??''});const form=el('form',{class:'form',onsubmit:async e=>{e.preventDefault();try{await api(group?`/groups/${encodeURIComponent(group.id)}`:'/groups',{method:group?'PATCH':'POST',body:{name:input.value}});dialog.close();dialog.remove();onDone();}catch(err){notify(errorCopy(err));}}},el('h2',{text:group?'Rename group':'Create group'}),el('label',{},'Name',input),el('div',{class:'actions'},el('button',{class:'primary',type:'submit',text:'Save'}),el('button',{type:'button',text:'Cancel',onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.showModal();input.focus();}
async function groupDetail(id){const root=el('div');shell(root,'groups');try{const[groupsData,usage]=await Promise.all([api('/groups'),api(`/usage/groups/${encodeURIComponent(id)}?range=${range}`)]);const group=list(groupsData,'groups').find(g=>g.id===id);if(!group)throw new DisplayError('Group not found.');root.append(heading(group.name,'Measured usage, adjustments, and combined total',[rangeTabs(()=>groupDetail(id))]),el('div',{class:'detail-grid'},usageDetails(usage),el('section',{class:'card'},adjustmentForm({groupId:id},()=>groupDetail(id)),el('hr'),el('button',{class:'danger',text:'Archive group',disabled:group.archivedAt!==null,onclick:async()=>{if(confirm(`Archive ${group.name}?`)){try{await api(`/groups/${encodeURIComponent(id)}`,{method:'DELETE',body:{}});location.hash='#/groups';}catch(e){notify(errorCopy(e));}}}}))));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
async function devices(){
  const root=el('div',{},heading('Devices','Connection state and measured clients',[el('a',{class:'button primary',href:'#/devices/add',text:'Add device'})]));shell(root,'devices');
  try{
    const data=await api('/devices'),deviceRows=list(data,'devices');
    const rows=deviceRows.length?deviceRows.map(d=>el('div',{class:'list-row'},
      el('div',{},el('a',{href:`#/devices/${encodeURIComponent(d.id)}`,text:d.name}),el('div',{class:'muted',text:d.currentGroupName??'Unassigned'})),
      el('div',{},status(d.state),el('div',{class:'muted',text:`Last seen: ${when(d.lastSeenAt)}`}))
    )):[el('div',{class:'empty',text:'No connected devices yet.'})];
    root.append(el('div',{class:'list'},...rows));
  }catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}
}
function profileRow(device,profile,onChange){
  const command=loginCommand(profile),details=[environmentLabel(profile.mode),`${fmt(profile.measured?.totalTokens)} measured tokens`,`Last activity: ${when(profile.lastActivityAt)}`];
  const action=profile.disabledAt?null:el('button',{class:'danger',type:'button',text:'Stop tracking','data-testid':`stop-${profile.accountId}`,onclick:()=>stopTrackingDialog(device,profile,onChange)});
  return el('div',{class:'profile-row','data-testid':`profile-${profile.accountId}`},el('div',{class:'profile-main'},el('div',{class:'profile-title'},el('a',{href:`#/accounts/${encodeURIComponent(profile.accountId)}`,text:profile.name}),status(profile.trackingState)),el('div',{class:'muted',text:details.join(' | ')}),profile.actual?.state==='quota_available'?el('div',{class:'positive',text:'Quota available'}):profile.actual?el('div',{class:'muted',text:'Quota unavailable'}):null,command?el('div',{class:'login-command'},el('strong',{text:'Run:'}),el('code',{text:command})):null),action);
}
function stopTrackingDialog(device,profile,onDone){
  const dialog=el('dialog',{'data-testid':'stop-tracking-dialog'}),form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');button.disabled=true;try{await api(`/devices/${encodeURIComponent(device.id)}/account-bindings/${encodeURIComponent(profile.id)}`,{method:'DELETE',body:{}});dialog.close();dialog.remove();notify('Tracking is stopping. Local Codex data was not changed.');await onDone();}catch(error){notify(errorCopy(error));button.disabled=false;}}},el('h2',{text:`Stop tracking ${profile.name} on this device?`}),el('p',{text:'Codex Meter will stop collecting new usage. Your Codex login and local data will not be deleted.'}),el('div',{class:'actions'},el('button',{class:'danger',type:'submit','data-testid':'confirm-stop',text:'Stop tracking'}),el('button',{type:'button',text:'Cancel',onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.isConnected)dialog.remove();});dialog.showModal();
}
function addAccountDialog(device,accounts,onDone){
  const activeProfiles=device.profiles.filter(profile=>!profile.disabledAt),activeIds=new Set(activeProfiles.map(profile=>profile.accountId)),available=accounts.filter(account=>!account.archivedAt&&!activeIds.has(account.id));
  const dialog=el('dialog',{'data-testid':'add-account-dialog'}),select=el('select',{required:true,'data-testid':'account-profile'},el('option',{value:'',text:'Select an Account Profile'}),...available.map(account=>el('option',{value:account.id,text:account.name}))),choice=environmentChoices({currentAvailable:!activeProfiles.some(profile=>profile.mode==='default'),testId:'account-environment'});
  const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();if(!select.value)return;const button=form.querySelector('[type="submit"]');button.disabled=true;try{await api(`/devices/${encodeURIComponent(device.id)}/account-bindings`,{method:'POST',body:{accountId:select.value,mode:choice.value()}});dialog.close();dialog.remove();notify('Account added. The Agent will apply it automatically.');await onDone();}catch(error){notify(errorCopy(error));button.disabled=false;}}},el('h2',{text:'Add account'}),el('label',{},'Account Profile',select),choice.field,el('div',{class:'actions'},el('button',{class:'primary',type:'submit','data-testid':'confirm-add-account',text:'Add account'}),el('button',{type:'button',text:'Cancel',onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.isConnected)dialog.remove();});dialog.showModal();select.focus();
}
async function deviceDetail(id){
  const root=el('div');shell(root,'devices');
  try{
    const[device,usage,groupsData,accountsData]=await Promise.all([api(`/devices/${encodeURIComponent(id)}`),api(`/usage/devices/${encodeURIComponent(id)}?range=${range}`),api('/groups'),api('/accounts?range=all')]);
    const profiles=list(device,'profiles'),groups=list(groupsData,'groups'),accountsList=list(accountsData,'accounts'),activeGroups=groups.filter(group=>!group.archivedAt);
    const group=el('select',{},el('option',{value:'',text:'Unassigned'}),...activeGroups.map(entry=>el('option',{value:entry.id,text:entry.name})));group.value=device.currentGroupId??'';
    const name=el('input',{value:device.name,required:true});
    const controls=el('form',{class:'form compact-form',onsubmit:async event=>{event.preventDefault();try{await api(`/devices/${encodeURIComponent(id)}`,{method:'PATCH',body:{name:name.value}});notify('Device renamed');deviceDetail(id);}catch(error){notify(errorCopy(error));}}},el('h2',{text:'Device controls'}),el('label',{},'Name',name),el('button',{type:'submit',text:'Rename'}),el('label',{},'Group',group),el('button',{type:'button',text:'Move device',onclick:async()=>{try{await api(`/devices/${encodeURIComponent(id)}/move`,{method:'POST',body:{groupId:group.value||null}});notify('Device moved');deviceDetail(id);}catch(error){notify(errorCopy(error));}}}),el('button',{type:'button',text:device.disabledAt?'Enable device':'Disable device',onclick:async()=>{try{await api(`/devices/${encodeURIComponent(id)}/disable`,{method:'POST',body:{disabled:!device.disabledAt}});deviceDetail(id);}catch(error){notify(errorCopy(error));}}}),el('button',{type:'button',text:'Rotate credential',onclick:async()=>{if(!confirm('The current Agent credential will stop working. Continue?'))return;try{const result=await api(`/devices/${encodeURIComponent(id)}/rotate`,{method:'POST',body:{}});secretDialog(result.deviceSecret);}catch(error){notify(errorCopy(error));}}}),el('button',{class:'danger',type:'button',text:'Remove device',onclick:async()=>{if(!confirm(`Permanently remove ${device.name}? Usage history remains.`))return;try{await api(`/devices/${encodeURIComponent(id)}`,{method:'DELETE',body:{}});location.hash='#/devices';}catch(error){notify(errorCopy(error));}}}));
    const activeIds=new Set(profiles.filter(profile=>!profile.disabledAt).map(profile=>profile.accountId)),available=accountsList.filter(account=>!account.archivedAt&&!activeIds.has(account.id));
    const add=el('button',{class:'primary',type:'button','data-testid':'add-account',text:'+ Add account',disabled:available.length===0,onclick:()=>addAccountDialog(device,accountsList,()=>deviceDetail(id))});
    const tracked=el(
      'section',
      {class:'profile-section','aria-labelledby':'tracked-accounts'},
      el('div',{class:'toolbar'},el('div',{},el('h2',{id:'tracked-accounts',text:'Tracked Codex accounts'}),el('div',{class:'muted',text:'Only accounts explicitly added here are measured.'})),add),
      el('div',{class:'profile-list'},...(profiles.length?profiles.map(profile=>profileRow(device,profile,()=>deviceDetail(id))):[el('div',{class:'empty',text:'No Codex accounts are tracked on this device.'})]))
    );
    root.append(heading(device.name,`${device.currentGroupName??'Unassigned'} | Last seen ${when(device.lastSeenAt)}`,[status(device.state),rangeTabs(()=>deviceDetail(id))]));
    if(device.configurationStatus==='apply_failed')root.append(el('div',{class:'notice error-notice',text:'Profile configuration could not be applied. Current tracking continues using the previous configuration.'}));
    root.append(tracked,el('div',{class:'detail-grid'},usageDetails(usage),el('section',{class:'card'},controls)),el('section',{class:'card'},adjustmentForm({deviceId:id},()=>deviceDetail(id))));
    if(profiles.some(profile=>['waiting_for_agent','applying','apply_failed','stop_tracking_pending'].includes(profile.trackingState))){pollTimer=setTimeout(()=>{if(location.hash===`#/devices/${encodeURIComponent(id)}`)deviceDetail(id);},3000);}
  }catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));}
}
function secretDialog(secret){const dialog=el('dialog',{},el('h2',{text:'New credential'}),el('div',{class:'notice',text:'Shown once. Update the Agent configuration securely.'}),el('div',{class:'code-line'},el('code',{text:secret}),el('button',{text:'Copy',onclick:()=>navigator.clipboard.writeText(secret)})),el('button',{text:'Close',onclick:()=>dialog.close()}));document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
async function addDevice(){
  if(pollTimer)clearTimeout(pollTimer);const root=el('div');shell(root,'devices');
  try{
    const[groupsData,accountsData]=await Promise.all([api('/groups'),api('/accounts?range=all')]),groups=list(groupsData,'groups'),accountsList=list(accountsData,'accounts').filter(account=>!account.archivedAt);
    const name=el('input',{required:true,maxlength:'200','data-testid':'device-name'});
    const group=el('select',{},el('option',{value:'',text:'Unassigned'}),...groups.filter(entry=>!entry.archivedAt).map(entry=>el('option',{value:entry.id,text:entry.name})));
    const profile=el('select',{required:true,'data-testid':'initial-account'},el('option',{value:'',text:'Select an Account Profile'}),...accountsList.map(account=>el('option',{value:account.id,text:account.name})));
    const choice=environmentChoices({testId:'initial-environment'});
    const form=el('form',{class:'form onboarding-form','data-testid':'add-device-form',onsubmit:async event=>{event.preventDefault();if(!profile.value)return;const button=form.querySelector('[type="submit"]');button.disabled=true;try{const enrollment=await api('/devices',{method:'POST',body:{name:name.value,groupId:group.value||null,accountId:profile.value,mode:choice.value()}});showEnrollment(root,enrollment);}catch(error){notify(errorCopy(error));button.disabled=false;}}},el('label',{},'Device name',name),el('label',{},'Group',group),el('label',{},'Account Profile',profile),choice.field,accountsList.length?null:el('div',{class:'notice',text:'Create an Account Profile before adding a device.'}),el('button',{class:'primary',type:'submit',disabled:accountsList.length===0,text:'Create device'}));
    root.append(heading('Add device','Choose the Codex account to track'),el('section',{class:'card onboarding-card'},form));
  }catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));}
}
function installerCommands(enrollment){
  if(!enrollment||typeof enrollment.enrollmentToken!=='string'||!/^[A-Za-z0-9_-]{20,200}$/.test(enrollment.enrollmentToken)||typeof enrollment.enrollmentId!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(enrollment.enrollmentId))throw new DisplayError('Unexpected Server response.');
  const parsed=new URL(location.origin),local=parsed.hostname==='127.0.0.1'||parsed.hostname==='localhost'||parsed.hostname==='::1';if(parsed.protocol!=='https:'&&!(parsed.protocol==='http:'&&local))throw new DisplayError('HTTPS is required for Agent installation.');const base=parsed.origin,token=enrollment.enrollmentToken,ps=value=>`'${value.replaceAll("'","''")}'`,sh=value=>`'${value.replaceAll("'","'\"'\"'")}'`;
  return[['Windows PowerShell',`& ([scriptblock]::Create((irm ${ps(`${base}/install.ps1`)}))) -ServerUrl ${ps(base)} -EnrollmentToken ${ps(token)}`],['Linux x64',`curl -fsSL ${sh(`${base}/install.sh`)} | sh -s -- --server ${sh(base)} --token ${sh(token)}`],['macOS arm64',`curl -fsSL ${sh(`${base}/install.sh`)} | sh -s -- --server ${sh(base)} --token ${sh(token)}`]];
}
function showEnrollment(root,enrollment){
  let commands;try{commands=installerCommands(enrollment);}catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));return;}
  const state=el('div',{class:'notice','data-testid':'enrollment-state',text:'Waiting for the Agent to connect...'}),card=el('section',{class:'card enrollment-card'},el('h2',{text:'Install and connect'}),el('p',{class:'muted',text:`Enrollment expires ${when(enrollment.expiresAt)}. The one-time token is shown only here.`}),...commands.map(([platform,command])=>el('div',{class:'install-command'},el('strong',{text:platform}),el('div',{class:'code-line'},el('code',{text:command,'data-testid':`command-${platform.split(' ')[0].toLowerCase()}`}),el('button',{type:'button',text:'Copy',onclick:()=>navigator.clipboard?.writeText(command)})))),state);
  root.replaceChildren(heading('Add device','Run one command on the device'),card);
  const poll=async()=>{try{const result=await api(`/device-enrollments/${encodeURIComponent(enrollment.enrollmentId)}`);if(result.status==='connected'&&typeof result.deviceId==='string'){state.className='notice success-notice';state.textContent='Agent connected.';state.append(el('a',{class:'button primary',href:`#/devices/${encodeURIComponent(result.deviceId)}`,text:'View device'}));return;}if(result.status==='expired'){state.textContent='Enrollment expired. Create a new device enrollment.';return;}if(result.status!=='pending')throw new DisplayError('Unexpected Server response.');}catch(error){state.textContent=`Connection check failed: ${errorCopy(error)}`;}pollTimer=setTimeout(poll,2000);};poll();
}
async function accounts(){
  const root=el('div');
  const add=el('button',{class:'primary',text:'New profile',onclick:()=>accountDialog(null,accounts)});
  root.append(heading('Accounts','Account Profiles and tracking coverage',[rangeTabs(accounts),add]));shell(root,'accounts');
  try{
    const data=await api(`/accounts?range=${range}`),accountRows=list(data,'accounts');
    const rows=accountRows.length?accountRows.map(account=>el('div',{class:'list-row'},
      el('div',{},el('a',{href:`#/accounts/${encodeURIComponent(account.id)}`,text:account.name}),el('div',{class:'muted',text:`${coverageCopy(account.trackingCoverage)}${account.reference?' | Reference profile':''}`})),
      el('div',{},status(account.quota.status),el('div',{class:'muted',text:`${fmt(account.measured.totalTokens)} measured tokens`}))
    )):[el('div',{class:'empty',text:'No Account Profiles yet.'})];
    root.append(el('div',{class:'list'},...rows));
  }catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}
}
function accountDialog(account,onDone){const dialog=el('dialog'),name=el('input',{required:true,maxlength:'200',value:account?.name??''}),reference=el('input',{type:'checkbox'});reference.checked=account?.reference??false;const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();try{await api(account?`/accounts/${encodeURIComponent(account.id)}`:'/accounts',{method:account?'PATCH':'POST',body:{name:name.value,reference:reference.checked}});dialog.close();dialog.remove();onDone();}catch(error){notify(errorCopy(error));}}},el('h2',{text:account?'Edit Account Profile':'Create Account Profile'}),el('p',{class:'muted',text:'This is a Meter label, not a verified provider identity.'}),el('label',{},'Profile name',name),el('label',{class:'check-label'},reference,' Reference profile'),el('div',{class:'actions'},el('button',{class:'primary',type:'submit',text:'Save'}),el('button',{type:'button',text:'Cancel',onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.showModal();name.focus();}
async function accountDetail(id){
  const root=el('div');shell(root,'accounts');
  try{
    const[account,attribution]=await Promise.all([api(`/accounts/${encodeURIComponent(id)}?range=${range}`),api(`/accounts/${encodeURIComponent(id)}/quota-attribution`)]),devicesList=list(account,'devices'),groupList=list(account,'groups');
    const edit=el('button',{text:'Edit',onclick:()=>accountDialog(account,()=>accountDetail(id))}),coverage=account.trackingCoverage;
    const coveragePanel=el('section',{class:'coverage-band'},el('div',{},el('div',{class:'metric-label',text:'Tracking coverage'}),el('div',{class:'big compact',text:coverageCopy(coverage)})),coverage?.status==='full'?status('tracking'):status(coverage?.status==='unknown'?'waiting_for_agent':'quota_unavailable'));
    const deviceRows=devicesList.length?devicesList.map(device=>el('div',{class:'list-row'},el('div',{},el('a',{href:`#/devices/${encodeURIComponent(device.deviceId)}`,text:device.name}),el('div',{class:'muted',text:`${environmentLabel(device.mode)} | Last activity: ${when(device.lastActivityAt)}`})),el('div',{class:'right'},status(device.trackingState),el('strong',{text:`${fmt(device.measured.totalTokens)} tokens`})))):[el('div',{class:'empty',text:'No registered devices.'})];
    root.append(heading(account.name,'Measured usage and registered Device coverage',[rangeTabs(()=>accountDetail(id)),edit]),coveragePanel,usageDetails({measured:account.measured,adjusted:{totalTokens:'0'},combined:{totalTokens:account.measured.totalTokens}}),cycleView({accounts:[account]},attribution),el('section',{class:'card'},el('h2',{text:'Tracked devices'}),...deviceRows),el('section',{class:'card'},el('h2',{text:'Group breakdown'}),...groupList.map(group=>el('div',{class:'list-row'},el('span',{text:group.name}),el('strong',{text:fmt(group.measured.totalTokens)}))),el('div',{class:'list-row'},el('span',{text:'Unassigned'}),el('strong',{text:fmt(account.unassigned.totalTokens)}))));
  }catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));}
}
async function settings(){const root=el('div');shell(root,'settings');try{const[data,devicesData]=await Promise.all([api('/settings'),api('/devices')]);const timezone=el('input',{value:data.timezone??'UTC',required:true}),reporter=el('select',{},el('option',{value:'',text:'None'}),...devicesData.devices.filter(d=>!d.disabledAt).map(d=>el('option',{value:d.id,text:d.name}))),online=el('input',{type:'number',min:'10',required:true,value:data.onlineThresholdSeconds}),stale=el('input',{type:'number',min:'11',max:'86400',required:true,value:data.staleThresholdSeconds});reporter.value=data.quotaReporterDeviceId??'';const form=el('form',{class:'form',onsubmit:async e=>{e.preventDefault();try{await api('/settings',{method:'PATCH',body:{timezone:timezone.value,quotaReporterDeviceId:reporter.value||null,onlineThresholdSeconds:Number(online.value),staleThresholdSeconds:Number(stale.value)}});notify('Settings saved');settings();}catch(err){notify(errorCopy(err));}}},el('label',{},'Aggregation timezone',timezone),el('label',{},'Quota reporter device',reporter),el('div',{class:'form-row'},el('label',{},'Online threshold (seconds)',online),el('label',{},'Offline threshold (seconds)',stale)),el('p',{class:'muted',text:'A device is Online below the first threshold, Stale between thresholds, and Offline above the second.'}),el('button',{class:'primary',type:'submit',text:'Save settings'}));root.append(heading('Settings','Timezone, quota reporter, and centralized device-state thresholds'),el('section',{class:'card'},form));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
async function route(){if(pollTimer){clearTimeout(pollTimer);pollTimer=null;}if(!csrf){try{const session=await api('/auth/session');csrf=session.csrfToken;}catch{return;}}const parts=(location.hash.replace(/^#\/?/,'')||'overview').split('/').map(decodeURIComponent);if(parts[0]==='overview')return overview();if(parts[0]==='groups'&&parts[1])return groupDetail(parts[1]);if(parts[0]==='groups')return groups();if(parts[0]==='devices'&&parts[1]==='add')return addDevice();if(parts[0]==='devices'&&parts[1])return deviceDetail(parts[1]);if(parts[0]==='devices')return devices();if(parts[0]==='accounts'&&parts[1])return accountDetail(parts[1]);if(parts[0]==='accounts')return accounts();if(parts[0]==='settings')return settings();location.hash='#/overview';}
window.addEventListener('hashchange',route);route();
