const app=document.querySelector('#app');const toast=document.querySelector('#toast');let csrf=null;let range='today';let pollTimer=null;let cycleAccountId=null;let cycleWindowKey=null;
const KOREAN={
  'Use an existing Codex environment':'기존 Codex 환경 사용','Track the default Codex environment on this device.':'이 기기의 기본 Codex 환경을 추적합니다.','Connect a Codex environment you already use on this device.':'이 기기에서 이미 사용하는 Codex 환경을 연결합니다.','Create a separate Codex environment for another account.':'다른 계정용으로 별도의 Codex 환경을 만듭니다.','Waiting for local environment selection':'기기에서 기존 환경 선택 대기 중','Waiting for a compatible Agent':'호환되는 에이전트 대기 중','On this device, run:':'해당 기기에서 실행하세요:','Use your existing Codex launcher to sign in.':'평소 사용하는 Codex 실행 명령으로 로그인하세요.','Update the Agent on this device to connect an existing environment.':'기존 환경을 연결하려면 해당 기기의 에이전트를 업데이트하세요.','Each tab is a provider-reported limit and reset period, not a separate local usage counter. Limit identifiers are shown as reported by the provider.':'각 탭은 제공자가 보고한 한도와 재설정 기간이며, 별도로 측정한 로컬 사용량이 아닙니다. 한도 이름은 제공자가 보낸 식별자 그대로 표시합니다.',
  'Registered. Waiting for the first Agent status report...':'기기 등록 완료. 에이전트의 첫 상태 보고를 기다리고 있습니다...','Status updates are temporarily unavailable. Retrying...':'상태 정보를 갱신할 수 없어 다시 시도하고 있습니다...',
  'Unexpected Server response.':'예기치 않은 서버 응답입니다.','The Server could not be reached.':'서버에 연결할 수 없습니다.','Your session expired.':'세션이 만료되었습니다.','Select an active Account Profile.':'활성 계정 프로필을 선택하세요.','Select how this Codex login is used.':'이 Codex 로그인의 사용 방식을 선택하세요.','That Account Profile is already tracked here, or this login option is already in use.':'이 계정 프로필은 이미 추적 중이거나 해당 로그인 방식이 사용 중입니다.','The existing local assignment could not be resumed.':'기존 로컬 할당을 다시 시작할 수 없습니다.','This enrollment expired. Create a new device enrollment.':'등록이 만료되었습니다. 새 기기 등록을 만드세요.','The request could not be completed.':'요청을 완료할 수 없습니다.',
  'Waiting for Agent':'에이전트 대기 중','Applying':'적용 중','Tracking':'추적 중','Login required':'로그인 필요','Quota unavailable':'할당량 확인 불가','Agent offline':'에이전트 오프라인','Apply failed':'적용 실패','Stopping':'중지 중','Not tracking':'추적 안 함','Online':'온라인','Offline':'오프라인','Stale':'응답 지연','Disabled':'비활성화됨','Available':'사용 가능','Unavailable':'사용 불가','Ambiguous':'확인 불가','Reporter offline':'보고 기기 오프라인','Collection failed':'수집 실패','Observation stale':'관측 정보 만료','No reporter':'보고 기기 없음','Never':'없음',
  "Using this device's current Codex login":'이 기기의 현재 Codex 로그인 사용','Separate Codex login':'별도의 Codex 로그인','Existing Codex login':'기존 Codex 로그인','Coverage unavailable':'추적 범위를 확인할 수 없음','{reporting} / {registered} registered device reporting':'등록된 기기 {registered}대 중 {reporting}대 보고 중','{reporting} / {registered} registered devices reporting':'등록된 기기 {registered}대 중 {reporting}대 보고 중','{devices} - estimate may be incomplete':'{devices} - 추정치가 불완전할 수 있음','Run':'실행',
  'How do you use this account?':'이 계정을 어떻게 사용하나요?',"Use this device's current Codex login":'이 기기의 현재 Codex 로그인 사용','The current login is already assigned.':'현재 로그인이 이미 할당되어 있습니다.','Add another Codex login':'다른 Codex 로그인 추가','Overview':'개요','Groups':'그룹','Devices':'기기','Accounts':'계정','Settings':'설정','Main navigation':'주 메뉴','Measured usage dashboard':'측정 사용량 대시보드','Log out':'로그아웃','Switch to Korean':'한국어로 전환','Switch to English':'영어로 전환','Administrator password':'관리자 비밀번호','Sign in':'로그인','Sign in to administer measured usage.':'측정 사용량을 관리하려면 로그인하세요.','Usage range':'사용량 기간','Today':'오늘','All':'전체',
  'Account Quota':'계정 할당량','{plan} plan':'{plan} 요금제','Provider quota status':'제공자 할당량 상태','No quota reporter is configured for this profile.':'이 프로필에 할당량 보고 기기가 설정되지 않았습니다.','The quota reporter is offline.':'할당량 보고 기기가 오프라인입니다.','The reporter is online, but quota collection failed{detail}.':'보고 기기는 온라인이지만 할당량 수집에 실패했습니다{detail}.','The last quota observation is stale. Last observed {time}.':'마지막 할당량 관측 정보가 오래되었습니다. 마지막 관측: {time}.','Quota windows are ambiguous; no current value was selected.':'할당량 구간을 판별할 수 없어 현재 값을 선택하지 못했습니다.','Quota is unavailable.':'할당량을 확인할 수 없습니다.','{limit} · {minutes} min':'{limit} · {minutes}분','{percent}% used':'{percent}% 사용','Resets {time}':'재설정: {time}','Reset time unavailable':'재설정 시간을 확인할 수 없음','Weekly':'주간','{minutes} min':'{minutes}분','Reset boundary passed':'재설정 시각이 지남','Resets in {distance}':'{distance} 후 재설정',
  'Account Profile':'계정 프로필','Account':'계정','Account: {name}':'계정: {name}','Profile':'프로필','Provider cycle view':'제공자 주기 보기','Current provider-defined quota cycle':'제공자가 정의한 현재 할당량 주기','No quota reporter is configured for this Account Profile.':'이 계정 프로필에 할당량 보고 기기가 설정되지 않았습니다.','The quota reporter is offline. Last observed {time}.':'할당량 보고 기기가 오프라인입니다. 마지막 관측: {time}.','Quota collection failed{detail}.':'할당량 수집에 실패했습니다{detail}.','Quota reporter state is unavailable.':'할당량 보고 기기 상태를 확인할 수 없습니다.','Cycle attribution unavailable':'주기별 배분을 확인할 수 없음','A valid provider reset boundary and quota observation are required.':'유효한 제공자 재설정 경계와 할당량 관측 정보가 필요합니다.','Estimated from tracked token usage. This is not provider-attributed usage.':'추적된 토큰 사용량을 바탕으로 한 추정치이며 제공자가 산정한 사용량이 아닙니다.','Provider quota window':'제공자 할당량 구간','Full cycle':'전체 주기','Partial - tracking began {time}':'부분 주기 - {time}부터 추적','Cycle boundary unavailable':'주기 경계를 확인할 수 없음','One or more registered devices are not reporting. The estimate may be incomplete.':'등록된 기기 중 보고하지 않는 기기가 있어 추정치가 불완전할 수 있습니다.','Current {window} Cycle':'현재 {window} 주기','Provider usage':'제공자 사용량','Tracking coverage':'추적 범위','Cycle coverage':'주기 범위','Reset':'재설정','Estimated from stale quota snapshot observed {time}.':'{time}에 관측된 오래된 할당량 정보를 바탕으로 추정했습니다.','Estimated quota contribution since tracking began':'추적 시작 이후 예상 할당량 기여도','Estimated quota contribution':'예상 할당량 기여도','tracked since coverage began':'추적 시작 이후 토큰','tracked tokens this cycle':'이번 주기에 추적된 토큰','Share of tracked usage':'추적 사용량 비율','Estimated by allocating provider-reported account usage in proportion to locally tracked token usage. This is not provider-attributed usage. Untracked devices or usage may make this estimate inaccurate.':'제공자가 보고한 계정 사용량을 로컬에서 추적한 토큰 사용량 비율로 배분한 추정치입니다. 제공자가 산정한 사용량이 아니며 추적되지 않은 기기나 사용량 때문에 부정확할 수 있습니다.',
  'Historical tracked usage':'과거 추적 사용량','Measured usage ranges; not provider quota attribution':'기간별 측정 사용량이며 제공자 할당량 배분이 아닙니다.','Unassigned':'미할당','combined tokens':'합산 토큰','Share of measured token usage':'측정 토큰 사용량 비율','Measured {measured} · Adjustments {adjusted}':'측정 {measured} · 조정 {adjusted}','Provider-cycle estimates and historical measured usage':'제공자 주기 추정치와 과거 측정 사용량','Create and bind an Account Profile to enable provider-cycle attribution.':'제공자 주기별 배분을 사용하려면 계정 프로필을 만들고 연결하세요.',
  'e.g. 100 or -50':'예: 100 또는 -50','Reason (required)':'사유(필수)','Adjustment recorded':'조정값을 기록했습니다.','Manual adjustment':'수동 조정','Adjustments remain separate from measured usage.':'조정값은 측정 사용량과 별도로 유지됩니다.','Token amount':'토큰 수량','Reason':'사유','Record adjustment':'조정 기록','Input':'입력','Cached input':'캐시된 입력','Cache-write input':'캐시 쓰기 입력','Output':'출력','Reasoning output':'추론 출력','Total':'합계','Measured':'측정','Adjustments':'조정','Combined':'합산','Measured token dimensions':'측정 토큰 항목',
  'New group':'새 그룹','Organize device attribution':'기기별 배분 구성','Rename':'이름 변경','No active groups.':'활성 그룹이 없습니다.','Archived':'보관됨','Rename group':'그룹 이름 변경','Create group':'그룹 만들기','Name':'이름','Save':'저장','Cancel':'취소','Group not found.':'그룹을 찾을 수 없습니다.','Measured usage, adjustments, and combined total':'측정 사용량, 조정값 및 합계','Archive group':'그룹 보관','Archive {name}?':'{name} 그룹을 보관할까요?',
  'Connection state and measured clients':'연결 상태와 측정 클라이언트','Add device':'기기 추가','Last seen: {time}':'마지막 연결: {time}','Remove':'제거','No connected devices yet.':'연결된 기기가 아직 없습니다.','Remove {name}?':'{name} 기기를 제거할까요?','Codex Meter will revoke this Device credential and remove it from active Devices. Historical usage remains. The local Agent and Codex data are not deleted.':'이 기기의 인증 정보를 폐기하고 활성 기기에서 제거합니다. 과거 사용 기록은 유지되며 로컬 에이전트 및 Codex 데이터는 삭제되지 않습니다.','Remove device':'기기 제거','Delete {name}?':'{name} 프로필을 삭제할까요?','Codex Meter will stop tracking this Profile on every Device and remove it from active Account Profiles. Historical usage and local Codex login data remain.':'모든 기기에서 이 프로필의 추적을 중지하고 활성 계정 프로필에서 제거합니다. 과거 사용 기록과 로컬 Codex 로그인 데이터는 유지됩니다.','Delete profile':'프로필 삭제','{tokens} measured tokens':'측정 토큰 {tokens}','Last activity: {time}':'마지막 활동: {time}','Stop tracking':'추적 중지','Quota available':'할당량 사용 가능','Stop tracking {name} on this device?':'이 기기에서 {name} 프로필 추적을 중지할까요?','Codex Meter will stop collecting new usage. Your Codex login and local data will not be deleted.':'새로운 사용량 수집을 중지합니다. Codex 로그인과 로컬 데이터는 삭제되지 않습니다.','Tracking is stopping. Local Codex data was not changed.':'추적을 중지하고 있습니다. 로컬 Codex 데이터는 변경되지 않았습니다.','Select an Account Profile':'계정 프로필 선택','Add account':'계정 추가','Account added. The Agent will apply it automatically.':'계정이 추가되었습니다. 에이전트가 자동으로 적용합니다.','Create another Account Profile before adding a Codex login.':'Codex 로그인을 추가하기 전에 다른 계정 프로필을 만드세요.','New profile':'새 프로필',
  'Device moved':'기기를 이동했습니다.','Device renamed':'기기 이름을 변경했습니다.','Device controls':'기기 제어','Move device':'기기 이동','Enable device':'기기 활성화','Disable device':'기기 비활성화','Rotate credential':'인증 정보 교체','The current Agent credential will stop working. Continue?':'현재 에이전트 인증 정보가 더 이상 작동하지 않습니다. 계속할까요?','+ Add account':'+ 계정 추가','Tracked Codex accounts':'추적 중인 Codex 계정','Only accounts explicitly added here are measured.':'여기에 명시적으로 추가한 계정만 측정합니다.','No Codex accounts are tracked on this device.':'이 기기에서 추적 중인 Codex 계정이 없습니다.','{group} | Last seen {time}':'{group} | 마지막 연결 {time}','Profile configuration could not be applied. Current tracking continues using the previous configuration.':'프로필 구성을 적용하지 못했습니다. 현재 추적은 이전 구성으로 계속됩니다.','New credential':'새 인증 정보','Shown once. Update the Agent configuration securely.':'한 번만 표시됩니다. 에이전트 구성을 안전하게 업데이트하세요.','Copy':'복사','Close':'닫기',
  'Device name':'기기 이름','Group':'그룹','Create an Account Profile before adding a device.':'기기를 추가하기 전에 계정 프로필을 만드세요.','Create device':'기기 만들기','Choose the Codex account to track':'추적할 Codex 계정을 선택하세요.','HTTPS is required for Agent installation.':'에이전트를 설치하려면 HTTPS가 필요합니다.','Waiting for the Agent to connect...':'에이전트 연결을 기다리는 중...','Install and connect':'설치 및 연결','Enrollment expires {time}. The one-time token is shown only here.':'등록 만료: {time}. 일회용 토큰은 여기에서만 표시됩니다.','Run one command on the device':'기기에서 명령 하나를 실행하세요.','Agent connected.':'에이전트가 연결되었습니다.','View device':'기기 보기','Enrollment expired. Create a new device enrollment.':'등록이 만료되었습니다. 새 기기 등록을 만드세요.','Connection check failed: {error}':'연결 확인 실패: {error}',
  'Account Profiles and tracking coverage':'계정 프로필과 추적 범위','Reference profile':'기준 프로필','{tokens} measured tokens':'측정 토큰 {tokens}','Delete':'삭제','No Account Profiles yet.':'계정 프로필이 아직 없습니다.','Edit Account Profile':'계정 프로필 편집','Create Account Profile':'계정 프로필 만들기','This is a Meter label, not a verified provider identity.':'Meter 내부 표시 이름이며 확인된 제공자 계정 정보가 아닙니다.','Profile name':'프로필 이름','Edit':'편집','{mode} | Last activity: {time}':'{mode} | 마지막 활동: {time}','{tokens} tokens':'토큰 {tokens}','No registered devices.':'등록된 기기가 없습니다.','Measured usage and registered Device coverage':'측정 사용량과 등록 기기 추적 범위','Tracked devices':'추적 기기','Group breakdown':'그룹별 내역',
  'None':'없음','Settings saved':'설정을 저장했습니다.','Aggregation timezone':'집계 시간대','Quota reporter device':'할당량 보고 기기','Online threshold (seconds)':'온라인 기준(초)','Offline threshold (seconds)':'오프라인 기준(초)','A device is Online below the first threshold, Stale between thresholds, and Offline above the second.':'기기는 첫 번째 기준보다 짧으면 온라인, 두 기준 사이면 응답 지연, 두 번째 기준보다 길면 오프라인으로 표시됩니다.','Save settings':'설정 저장','Timezone, quota reporter, and centralized device-state thresholds':'시간대, 할당량 보고 기기 및 중앙 기기 상태 기준','Skip to content':'본문으로 건너뛰기'
};
function storedLanguage(){const saved=document.cookie.match(/(?:^|;\s*)codex_meter_language=(en|ko)(?:;|$)/)?.[1];return saved??(String(navigator.language??'').toLowerCase().startsWith('ko')?'ko':'en');}
let language=storedLanguage();
function t(key,values={}){const template=language==='ko'?(KOREAN[key]??key):key;return template.replace(/\{([a-z]+)\}/gi,(_match,name)=>String(values[name]??''));}
function applyDocumentLanguage(){document.documentElement.lang=language;const skip=document.querySelector('.skip');if(skip)skip.textContent=t('Skip to content');}
function setLanguage(next){language=next;document.cookie=`codex_meter_language=${language}; Path=/; Max-Age=31536000; SameSite=Strict${location.protocol==='https:'?'; Secure':''}`;applyDocumentLanguage();if(csrf)route();else renderLogin();}
function languageToggle(){const next=language==='en'?'ko':'en',label=next==='ko'?'한국어':'English';return el('button',{class:'language-toggle',type:'button','data-testid':'language-toggle','aria-label':t(next==='ko'?'Switch to Korean':'Switch to English'),text:label,onclick:()=>setLanguage(next)});}
class DisplayError extends Error{}const errorCopy=error=>error instanceof DisplayError?error.message:t('Unexpected Server response.');
const el=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key==='text')node.textContent=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==null&&value!==false)node.setAttribute(key,value===true?'':String(value));}for(const child of children.flat()){if(child!==null&&child!==undefined)node.append(child instanceof Node?child:document.createTextNode(String(child)));}return node;};
function clear(node=app){node.replaceChildren();}function notify(message){toast.textContent=message;toast.hidden=false;setTimeout(()=>{toast.hidden=true;},3500);}function fmt(value){try{return BigInt(value).toLocaleString(language==='ko'?'ko-KR':'en-US');}catch{return '—';}}function when(value){return value?new Date(value).toLocaleString(language==='ko'?'ko-KR':'en-US'):t('Never');}
async function api(path,options={}){const init={credentials:'same-origin',headers:{accept:'application/json'},...options};if(options.body!==undefined){init.headers={...init.headers,'content-type':'application/json','x-csrf-token':csrf};init.body=JSON.stringify(options.body);}let response;try{response=await fetch(`/api/v1${path}`,init);}catch{throw new DisplayError(t('The Server could not be reached.'));}let data={};try{data=await response.json();}catch{}if(response.status===401){csrf=null;renderLogin();throw new DisplayError(t('Your session expired.'));}if(!response.ok){const copies={invalid_account:'Select an active Account Profile.',invalid_mode:'Select how this Codex login is used.',binding_exists_or_mode_conflict:'That Account Profile is already tracked here, or this login option is already in use.',binding_identity_conflict:'The existing local assignment could not be resumed.',enrollment_expired:'This enrollment expired. Create a new device enrollment.'};throw new DisplayError(t(copies[data.error]??'The request could not be completed.'));}return data;}
const STATUS_LABELS={local_selection_required:'Waiting for local environment selection',waiting_for_compatible_agent:'Waiting for a compatible Agent',waiting_for_agent:'Waiting for Agent',applying:'Applying',tracking:'Tracking',login_required:'Login required',quota_unavailable:'Quota unavailable',agent_offline:'Agent offline',apply_failed:'Apply failed',stop_tracking_pending:'Stopping',stopped:'Not tracking',online:'Online',offline:'Offline',stale:'Stale',disabled:'Disabled',available:'Available',unavailable:'Unavailable',ambiguous:'Ambiguous',reporter_offline:'Reporter offline',collection_failed:'Collection failed',stale_observation:'Observation stale',no_reporter:'No reporter'};
function status(value){const raw=String(value??'unknown'),label=STATUS_LABELS[raw]?t(STATUS_LABELS[raw]):raw.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase());return el('span',{class:`status ${raw}`,text:label});}function heading(title,subtitle,actions=[]){return el('div',{class:'toolbar'},el('div',{},el('h1',{text:title}),el('div',{class:'subtitle',text:subtitle})),el('div',{class:'actions'},actions));}
function list(value,key){if(!value||!Array.isArray(value[key]))throw new DisplayError(t('Unexpected Server response.'));return value[key];}
function environmentLabel(mode){return t(mode==='default'?"Using this device's current Codex login":mode==='isolated'?'Separate Codex login':'Existing Codex login');}
function coverageCopy(coverage){if(!coverage||!Number.isSafeInteger(coverage.registeredDevices)||!Number.isSafeInteger(coverage.reportingDevices))return t('Coverage unavailable');const key=coverage.registeredDevices===1?'{reporting} / {registered} registered device reporting':'{reporting} / {registered} registered devices reporting',devices=t(key,{reporting:coverage.reportingDevices,registered:coverage.registeredDevices});return coverage.status==='full'?devices:t('{devices} - estimate may be incomplete',{devices});}
function loginCommands(profile){
  if(profile.trackingState!=='login_required')return[];
  const launcher=profile.actual?.launcher;
  if(!launcher)return profile.mode==='default'?[[t('Run'),'codex login']]:[];
  if(!/^cx[1-9][0-9]{0,2}$/.test(launcher))throw new DisplayError(t('Unexpected Server response.'));
  return[['Linux',`"$HOME/.local/bin/${launcher}" login`],['macOS',`"$HOME/Library/Application Support/Codex Meter/${launcher}" login`],['Windows PowerShell',`& "$env:LOCALAPPDATA\\CodexMeter\\${launcher}.ps1" login`]];
}
function environmentChoices({currentAvailable=true,testId='environment',selectedMode=null}={}){
  const options=[['default','current',"Use this device's current Codex login",'Track the default Codex environment on this device.'],['existing','existing','Use an existing Codex environment','Connect a Codex environment you already use on this device.'],['isolated','separate','Add another Codex login','Create a separate Codex environment for another account.']];
  const selected=selectedMode&&!(selectedMode==='default'&&!currentAvailable)?selectedMode:currentAvailable?'default':'isolated';
  const inputs=options.map(([mode,id])=>{const input=el('input',{type:'radio',name:testId,value:mode,'data-testid':`${testId}-${id}`});input.disabled=mode==='default'&&!currentAvailable;input.checked=mode===selected;return input;});
  const field=el('fieldset',{class:'choice-group'},el('legend',{text:t('How do you use this account?')}),...options.map(([mode,_id,label,description],index)=>el('label',{class:`choice-option${inputs[index].disabled?' disabled':''}`},inputs[index],el('span',{},el('strong',{text:t(label)}),el('small',{text:t(inputs[index].disabled?'The current login is already assigned.':description)})))));
  return{field,value:()=>inputs.find(input=>input.checked)?.value};
}
function shell(content,current){clear();const links=[['overview','Overview'],['groups','Groups'],['devices','Devices'],['accounts','Accounts'],['settings','Settings']];const nav=el('nav',{class:'nav','aria-label':t('Main navigation')},...links.map(([id,label])=>el('a',{href:`#/${id}`,'aria-current':current===id?'page':null,text:t(label)})));const logout=el('button',{class:'logout',text:t('Log out'),onclick:async()=>{try{await api('/auth/logout',{method:'POST',body:{}});}finally{csrf=null;renderLogin();}}});app.append(el('div',{class:'shell'},el('aside',{class:'sidebar'},el('div',{class:'brand'},'Codex Meter',el('small',{text:t('Measured usage dashboard')})),nav,el('div',{class:'sidebar-footer'},languageToggle(),logout)),el('main',{class:'main',id:'main'},content)));}
function renderLogin(message=''){clear();const password=el('input',{type:'password',name:'password',autocomplete:'current-password',required:true,minlength:'12'});const error=el('p',{class:'error',text:message});const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();error.textContent='';const button=form.querySelector('[type="submit"]');button.disabled=true;try{const result=await api('/auth/login',{method:'POST',body:{password:password.value}});csrf=result.csrfToken;location.hash='#/overview';await route();}catch(e){error.textContent=errorCopy(e);}finally{button.disabled=false;}}},el('label',{},t('Administrator password'),password),error,el('button',{class:'primary',type:'submit',text:t('Sign in')}));app.append(el('main',{class:'login',id:'main'},el('div',{class:'login-panel'},el('div',{class:'login-language'},languageToggle()),el('section',{class:'card','aria-labelledby':'login-title'},el('h1',{id:'login-title',text:'Codex Meter'}),el('p',{class:'muted',text:t('Sign in to administer measured usage.')}),form))));password.focus();}
function rangeTabs(onchange){return el('div',{class:'tabs','aria-label':t('Usage range')},...[['today','Today'],['7d','7D'],['30d','30D'],['all','All']].map(([value,label])=>el('button',{type:'button','aria-pressed':range===value,text:t(label),onclick:()=>{range=value;onchange();}})));}
function quotaCard(quota){const card=el('section',{class:'card quota','aria-labelledby':'quota-title'},el('div',{class:'toolbar'},el('div',{},el('h2',{id:'quota-title',text:t('Account Quota')}),el('div',{class:'muted',text:quota.planType?t('{plan} plan',{plan:quota.planType}):t('Provider quota status')})),status(quota.status)));if(quota.reporterState!=='available'){const detail=quota.errorKind?` (${quota.errorKind.replaceAll('_',' ')})`:'';const copies={no_reporter:t('No quota reporter is configured for this profile.'),reporter_offline:t('The quota reporter is offline.'),collection_failed:t('The reporter is online, but quota collection failed{detail}.',{detail}),stale_observation:t('The last quota observation is stale. Last observed {time}.',{time:when(quota.observedAt)})};const copy=copies[quota.reporterState]??t(quota.status==='ambiguous'?'Quota windows are ambiguous; no current value was selected.':'Quota is unavailable.');card.append(el('div',{class:'notice',text:copy}));}if(quota.windows?.length){card.append(el('div',{class:'quota-grid'},...quota.windows.map(window=>{const used=t('{percent}% used',{percent:window.usedPercent});return el('div',{class:'quota-window'},el('div',{class:'metric-label',text:t('{limit} · {minutes} min',{limit:window.limitId,minutes:window.durationMinutes})}),el('div',{class:'big',text:used}),el('progress',{class:'meter',max:'100',value:String(Math.max(0,Math.min(100,window.usedPercent))),'aria-label':used}),el('div',{class:'muted',text:window.resetsAt?t('Resets {time}',{time:when(window.resetsAt)}):t('Reset time unavailable')}));})));}return card;}
function quotaWindowKey(window){return `${window.limitId}\u0000${window.durationMinutes}`;}
function quotaWindowLabel(window){if(window.durationMinutes===300)return'5H';if(window.durationMinutes===10080)return t('Weekly');const minutes=window.durationMinutes;return minutes%1440===0?`${minutes/1440}D`:minutes%60===0?`${minutes/60}H`:t('{minutes} min',{minutes});}
function resetDistance(value){if(!value)return t('Reset time unavailable');const milliseconds=Date.parse(value)-Date.now();if(milliseconds<=0)return t('Reset boundary passed');const minutes=Math.ceil(milliseconds/60000),days=Math.floor(minutes/1440),hours=Math.floor((minutes%1440)/60),rest=minutes%60;const distance=language==='ko'?`${days?`${days}일 `:''}${hours?`${hours}시간 `:''}${rest}분`:`${days?`${days}d `:''}${hours?`${hours}h `:''}${rest}m`;return t('Resets in {distance}',{distance});}
function cycleView(accountsData,attribution){
  const activeAccounts=accountsData.accounts.filter(account=>!account.archivedAt),account=activeAccounts.find(item=>item.id===attribution.accountId);
  const accountSelect=el('select',{'aria-label':t('Account Profile')},...activeAccounts.map(item=>el('option',{value:item.id,text:item.name})));
  accountSelect.value=attribution.accountId;accountSelect.addEventListener('change',()=>{cycleAccountId=accountSelect.value;cycleWindowKey=null;overview();});
  const controls=activeAccounts.length>1?el('label',{class:'inline-control'},el('span',{class:'metric-label',text:t('Account')}),accountSelect):el('div',{class:'metric-label',text:t('Account: {name}',{name:account?.name??t('Profile')})});
  const section=el('section',{class:'provider-cycle','aria-labelledby':'cycle-heading'},el('div',{class:'toolbar'},el('div',{},el('h2',{id:'cycle-heading',text:t('Provider cycle view')}),el('div',{class:'muted',text:t('Current provider-defined quota cycle')})),controls));
  const detail=attribution.quota.errorKind?` (${attribution.quota.errorKind.replaceAll('_',' ')})`:'';const reporterCopies={no_reporter:t('No quota reporter is configured for this Account Profile.'),reporter_offline:t('The quota reporter is offline. Last observed {time}.',{time:when(attribution.quota.observedAt)}),collection_failed:t('Quota collection failed{detail}.',{detail}),stale_observation:t('The last quota observation is stale. Last observed {time}.',{time:when(attribution.quota.observedAt)})};
  const reporterNotice=attribution.quota.reporterState==='available'?null:el('div',{class:'notice',text:reporterCopies[attribution.quota.reporterState]??t('Quota reporter state is unavailable.')});
  const badge=attribution.quota.reporterState==='available'?attribution.quota.status:attribution.quota.reporterState;
  if(!attribution.windows.length){section.append(el('div',{class:'card'},el('div',{class:'toolbar'},el('h2',{text:t('Cycle attribution unavailable')}),status(badge)),reporterNotice,el('p',{class:'muted',text:t('A valid provider reset boundary and quota observation are required.')}),el('div',{class:'notice',text:t('Estimated from tracked token usage. This is not provider-attributed usage.')})));return section;}
  if(!attribution.windows.some(window=>quotaWindowKey(window)===cycleWindowKey))cycleWindowKey=quotaWindowKey(attribution.windows[0]);
  const window=attribution.windows.find(item=>quotaWindowKey(item)===cycleWindowKey);
  const tabs=el('div',{class:'tabs','aria-label':t('Provider quota window')},...attribution.windows.map(item=>{const key=quotaWindowKey(item);return el('button',{type:'button','aria-pressed':String(key===cycleWindowKey),text:`${item.limitId} · ${quotaWindowLabel(item)}`,onclick:()=>{cycleWindowKey=key;overview();}});}));
  const cycleCoverage=window.coverage.status==='full'?t('Full cycle'):window.coverage.status==='partial'?t('Partial - tracking began {time}',{time:when(window.coverage.from)}):t('Cycle boundary unavailable');
  const trackingCoverage=coverageCopy(account?.trackingCoverage);
  const quotaValue=window.usedPercent===null?t('Unavailable'):t('{percent}% used',{percent:window.usedPercent});
  const staleNotice=window.estimate.status==='stale'&&attribution.quota.reporterState!=='stale_observation'?el('div',{class:'notice',text:t('Estimated from stale quota snapshot observed {time}.',{time:when(window.estimate.basedOnObservedAt)})}):null;
  const coverageNotice=account?.trackingCoverage?.status!=='full'?el('div',{class:'notice',text:t('One or more registered devices are not reporting. The estimate may be incomplete.')}):null;
  const summary=el('section',{class:'card cycle-summary'},el('div',{class:'toolbar'},el('div',{},el('h2',{text:t('Current {window} Cycle',{window:`${window.limitId} · ${quotaWindowLabel(window)}`})}),el('div',{class:'muted',text:account?.name??t('Account Profile')})),status(badge)),reporterNotice,el('div',{class:'metric-grid'},el('div',{},el('div',{class:'metric-label',text:t('Provider usage')}),el('div',{class:'big',text:quotaValue})),el('div',{},el('div',{class:'metric-label',text:t('Tracking coverage')}),el('div',{class:'big compact',text:trackingCoverage})),el('div',{},el('div',{class:'metric-label',text:t('Cycle coverage')}),el('div',{class:'big compact',text:cycleCoverage})),el('div',{},el('div',{class:'metric-label',text:t('Reset')}),el('div',{class:'big compact',text:resetDistance(window.resetsAt)}))),coverageNotice,staleNotice);
  const cards=window.groups.map(entry=>{const contribution=entry.estimatedQuotaContributionPercentagePoints;const estimateText=contribution===null?t('Unavailable'):`~${contribution.toFixed(1)}%p`;const estimateLabel=t(window.coverage.status==='partial'?'Estimated quota contribution since tracking began':'Estimated quota contribution');return el('article',{class:'card'},el('h2',{text:entry.group?entry.label:t('Unassigned')}),el('div',{class:'big',text:fmt(entry.trackedTokens)}),el('div',{class:'muted',text:t(window.coverage.status==='partial'?'tracked since coverage began':'tracked tokens this cycle')}),el('div',{class:'metric-label',text:t('Share of tracked usage')}),el('div',{class:'big',text:entry.trackedSharePercent===null?'—':`${entry.trackedSharePercent.toFixed(2)}%`}),el('div',{class:'metric-label',text:estimateLabel}),el('div',{class:'big',text:estimateText}));});
  section.append(tabs,el('p',{class:'muted',text:t('Each tab is a provider-reported limit and reset period, not a separate local usage counter. Limit identifiers are shown as reported by the provider.')}),summary,el('div',{class:'grid'},...cards),el('div',{class:'notice',text:t('Estimated by allocating provider-reported account usage in proportion to locally tracked token usage. This is not provider-attributed usage. Untracked devices or usage may make this estimate inaccurate.')}));return section;
}
function historicalView(summary){return el('section',{'aria-labelledby':'historical-heading'},el('div',{class:'toolbar'},el('div',{},el('h2',{id:'historical-heading',text:t('Historical tracked usage')}),el('div',{class:'muted',text:t('Measured usage ranges; not provider quota attribution')})),rangeTabs(overview)),el('div',{class:'grid'},...summary.groups.map(entry=>{const name=entry.group?.name??t('Unassigned');return el('a',{class:'card card-link',href:entry.group?`#/groups/${encodeURIComponent(entry.group.id)}`:'#/groups'},el('h2',{text:name}),el('div',{class:'big',text:fmt(entry.combined.totalTokens)}),el('div',{class:'muted',text:t('combined tokens')}),el('div',{class:'metric-label',text:t('Share of measured token usage')}),el('div',{class:'big',text:`${entry.shares.measured.toFixed(2)}%`}),el('div',{class:'muted',text:t('Measured {measured} · Adjustments {adjusted}',{measured:fmt(entry.measured.totalTokens),adjusted:fmt(entry.adjusted.totalTokens)})}));})));
}
async function overview(){const root=el('div',{},heading(t('Overview'),t('Provider-cycle estimates and historical measured usage')));shell(root,'overview');try{const accountsData=await api('/accounts?range=all');const active=list(accountsData,'accounts').filter(account=>!account.archivedAt);if(!active.some(account=>account.id===cycleAccountId))cycleAccountId=(active.find(account=>account.reference)??active[0])?.id??null;const requests=[api(`/usage/summary?range=${range}`)];if(cycleAccountId)requests.push(api(`/accounts/${encodeURIComponent(cycleAccountId)}/quota-attribution`));const[summary,attribution]=await Promise.all(requests);if(attribution)root.append(cycleView(accountsData,attribution));else root.append(el('div',{class:'notice',text:t('Create and bind an Account Profile to enable provider-cycle attribution.')}));root.append(historicalView(summary));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
function adjustmentForm(scope,onDone){const amount=el('input',{required:true,inputmode:'numeric',placeholder:t('e.g. 100 or -50')}),reason=el('textarea',{required:true,maxlength:'500',placeholder:t('Reason (required)')});return el('form',{class:'form',onsubmit:async event=>{event.preventDefault();try{await api('/usage/adjustments',{method:'POST',body:{...scope,amountTokens:amount.value,reason:reason.value,occurredAt:new Date().toISOString()}});notify(t('Adjustment recorded'));onDone();}catch(e){notify(errorCopy(e));}}},el('h2',{text:t('Manual adjustment')}),el('p',{class:'muted',text:t('Adjustments remain separate from measured usage.')}),el('label',{},t('Token amount'),amount),el('label',{},t('Reason'),reason),el('button',{class:'primary',type:'submit',text:t('Record adjustment')}));}
function usageDetails(data){const dims=[['inputTokens','Input'],['cachedInputTokens','Cached input'],['cacheWriteInputTokens','Cache-write input'],['outputTokens','Output'],['reasoningOutputTokens','Reasoning output'],['totalTokens','Total']];return el('section',{class:'card'},el('div',{class:'split'},...[[data.measured.totalTokens,'Measured'],[data.adjusted.totalTokens,'Adjustments'],[data.combined.totalTokens,'Combined']].map(([v,n])=>el('div',{},el('div',{class:'metric-label',text:t(n)}),el('div',{class:'big',text:fmt(v)})))),el('h2',{text:t('Measured token dimensions')}),el('div',{class:'dimensions'},...dims.map(([key,label])=>el('div',{class:'dimension'},el('span',{class:'muted',text:t(label)}),el('strong',{text:fmt(data.measured[key])})))));}
async function groups(){const root=el('div');const add=el('button',{class:'primary',text:t('New group'),onclick:()=>groupDialog(null,groups)});root.append(heading(t('Groups'),t('Organize device attribution'),[add]));shell(root,'groups');try{const data=await api('/groups'),groupRows=list(data,'groups');const active=groupRows.filter(g=>!g.archivedAt),archived=groupRows.filter(g=>g.archivedAt);root.append(el('div',{class:'list'},...(active.length?active.map(g=>el('div',{class:'list-row'},el('a',{href:`#/groups/${encodeURIComponent(g.id)}`,text:g.name}),el('button',{text:t('Rename'),onclick:()=>groupDialog(g,groups)}))):[el('div',{class:'empty',text:t('No active groups.')})])));if(archived.length)root.append(el('section',{class:'card'},el('h2',{text:t('Archived')}),...archived.map(g=>el('div',{class:'muted',text:g.name}))));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
function groupDialog(group,onDone){const dialog=el('dialog'),input=el('input',{required:true,maxlength:'200',value:group?.name??''});const form=el('form',{class:'form',onsubmit:async e=>{e.preventDefault();try{await api(group?`/groups/${encodeURIComponent(group.id)}`:'/groups',{method:group?'PATCH':'POST',body:{name:input.value}});dialog.close();dialog.remove();onDone();}catch(err){notify(errorCopy(err));}}},el('h2',{text:t(group?'Rename group':'Create group')}),el('label',{},t('Name'),input),el('div',{class:'actions'},el('button',{class:'primary',type:'submit',text:t('Save')}),el('button',{type:'button',text:t('Cancel'),onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.showModal();input.focus();}
async function groupDetail(id){const root=el('div');shell(root,'groups');try{const[groupsData,usage]=await Promise.all([api('/groups'),api(`/usage/groups/${encodeURIComponent(id)}?range=${range}`)]);const group=list(groupsData,'groups').find(g=>g.id===id);if(!group)throw new DisplayError(t('Group not found.'));root.append(heading(group.name,t('Measured usage, adjustments, and combined total'),[rangeTabs(()=>groupDetail(id))]),el('div',{class:'detail-grid'},usageDetails(usage),el('section',{class:'card'},adjustmentForm({groupId:id},()=>groupDetail(id)),el('hr'),el('button',{class:'danger',text:t('Archive group'),disabled:group.archivedAt!==null,onclick:async()=>{if(confirm(t('Archive {name}?',{name:group.name}))){try{await api(`/groups/${encodeURIComponent(id)}`,{method:'DELETE',body:{}});location.hash='#/groups';}catch(e){notify(errorCopy(e));}}}}))));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
async function devices(){
  const root=el('div',{},heading(t('Devices'),t('Connection state and measured clients'),[el('a',{class:'button primary',href:'#/devices/add',text:t('Add device')})]));shell(root,'devices');
  try{
    const data=await api('/devices'),deviceRows=list(data,'devices');
    const rows=deviceRows.length?deviceRows.map(d=>el('div',{class:'list-row'},
      el('div',{},el('a',{href:`#/devices/${encodeURIComponent(d.id)}`,text:d.name}),el('div',{class:'muted',text:d.currentGroupName??t('Unassigned')})),
      el('div',{class:'right'},status(d.state),el('div',{class:'muted',text:t('Last seen: {time}',{time:when(d.lastSeenAt)})}),el('button',{class:'danger',type:'button',text:t('Remove'),'data-testid':`remove-device-${d.id}`,onclick:()=>removeDeviceDialog(d,devices)}))
    )):[el('div',{class:'empty',text:t('No connected devices yet.')})];
    root.append(el('div',{class:'list'},...rows));
  }catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}
}
function destructiveDialog({testId,title,message,confirmText,onConfirm,onDone}){
  const dialog=el('dialog',{'data-testid':testId});let pending=false;
  const confirmButton=el('button',{class:'danger',type:'submit','data-testid':`confirm-${testId}`,text:confirmText}),cancel=el('button',{type:'button',text:t('Cancel'),onclick:()=>dialog.close()});
  const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();if(pending)return;pending=true;confirmButton.disabled=true;cancel.disabled=true;try{await onConfirm();dialog.close();dialog.remove();await onDone();}catch(error){notify(errorCopy(error));pending=false;confirmButton.disabled=false;cancel.disabled=false;}}},el('h2',{text:title}),el('p',{text:message}),el('div',{class:'actions'},confirmButton,cancel));
  dialog.append(form);document.body.append(dialog);dialog.addEventListener('cancel',event=>{if(pending)event.preventDefault();});dialog.addEventListener('close',()=>{if(dialog.isConnected)dialog.remove();});dialog.showModal();confirmButton.focus();
}
function removeDeviceDialog(device,onDone){
  destructiveDialog({testId:'remove-device-dialog',title:t('Remove {name}?',{name:device.name}),message:t('Codex Meter will revoke this Device credential and remove it from active Devices. Historical usage remains. The local Agent and Codex data are not deleted.'),confirmText:t('Remove device'),onConfirm:()=>api(`/devices/${encodeURIComponent(device.id)}`,{method:'DELETE',body:{}}),onDone});
}
function deleteAccountDialog(account,onDone){
  destructiveDialog({testId:'delete-account-dialog',title:t('Delete {name}?',{name:account.name}),message:t('Codex Meter will stop tracking this Profile on every Device and remove it from active Account Profiles. Historical usage and local Codex login data remain.'),confirmText:t('Delete profile'),onConfirm:()=>api(`/accounts/${encodeURIComponent(account.id)}`,{method:'DELETE',body:{}}),onDone});
}
function profileRow(device,profile,onChange){
  const commands=loginCommands(profile),details=[environmentLabel(profile.mode),t('{tokens} measured tokens',{tokens:fmt(profile.measured?.totalTokens)}),t('Last activity: {time}',{time:when(profile.lastActivityAt)})];
  const action=profile.disabledAt?null:el('button',{class:'danger',type:'button',text:t('Stop tracking'),'data-testid':`stop-${profile.accountId}`,onclick:()=>stopTrackingDialog(device,device.profiles.find(entry=>entry.id===profile.id)??profile,onChange)});
  const login=commands.length?el('div',{class:'login-commands'},...commands.map(([platform,command])=>el('div',{class:'login-command'},el('strong',{text:`${platform}:`}),el('code',{text:command})))):null;
  const selection=profile.mode==='existing'&&profile.trackingState==='local_selection_required'?el('div',{class:'notice'},t('On this device, run:'),el('code',{text:'codex-meter-agent profile attach-existing'})):profile.mode==='existing'&&profile.trackingState==='login_required'?el('div',{class:'notice',text:t('Use your existing Codex launcher to sign in.')}):profile.trackingState==='waiting_for_compatible_agent'?el('div',{class:'notice',text:t('Update the Agent on this device to connect an existing environment.')}):null;
  return el('div',{class:'profile-row','data-testid':`profile-${profile.accountId}`},el('div',{class:'profile-main'},el('div',{class:'profile-title'},el('a',{href:`#/accounts/${encodeURIComponent(profile.accountId)}`,text:profile.name}),status(profile.trackingState)),el('div',{class:'muted',text:details.join(' | ')}),profile.actual?.state==='quota_available'?el('div',{class:'positive',text:t('Quota available')}):profile.actual?el('div',{class:'muted',text:t('Quota unavailable')}):null,login,selection),action);
}
function stopTrackingDialog(device,profile,onDone){
  const dialog=el('dialog',{'data-testid':'stop-tracking-dialog'}),form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');button.disabled=true;try{await api(`/devices/${encodeURIComponent(device.id)}/account-bindings/${encodeURIComponent(profile.id)}`,{method:'DELETE',body:{}});dialog.close();dialog.remove();notify(t('Tracking is stopping. Local Codex data was not changed.'));await onDone();}catch(error){notify(errorCopy(error));button.disabled=false;}}},el('h2',{text:t('Stop tracking {name} on this device?',{name:profile.name})}),el('p',{text:t('Codex Meter will stop collecting new usage. Your Codex login and local data will not be deleted.')}),el('div',{class:'actions'},el('button',{class:'danger',type:'submit','data-testid':'confirm-stop',text:t('Stop tracking')}),el('button',{type:'button',text:t('Cancel'),onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.isConnected)dialog.remove();});dialog.showModal();
}
function addAccountDialog(device,accounts,onDone,preferredAccountId=null,selectedMode=null){
  const activeProfiles=device.profiles.filter(profile=>!profile.disabledAt),activeIds=new Set(activeProfiles.map(profile=>profile.accountId)),available=accounts.filter(account=>!account.archivedAt&&!activeIds.has(account.id));
  const dialog=el('dialog',{'data-testid':'add-account-dialog'}),select=el('select',{required:true,'data-testid':'account-profile'},el('option',{value:'',text:t('Select an Account Profile')}),...available.map(account=>el('option',{value:account.id,text:account.name}))),choice=environmentChoices({currentAvailable:!activeProfiles.some(profile=>profile.mode==='default'),testId:'account-environment',selectedMode});
  if(available.some(account=>account.id===preferredAccountId))select.value=preferredAccountId;
  const submit=el('button',{class:'primary',type:'submit','data-testid':'confirm-add-account',text:t('Add account'),disabled:!select.value});
  select.addEventListener('change',()=>{submit.disabled=!select.value;});
  const createProfile=()=>{const accountId=select.value,mode=choice.value();dialog.close();dialog.remove();accountDialog(null,created=>addAccountDialog(device,[...accounts,created],onDone,created.id,mode),()=>addAccountDialog(device,accounts,onDone,accountId,mode));};
  const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();if(!select.value)return;submit.disabled=true;try{await api(`/devices/${encodeURIComponent(device.id)}/account-bindings`,{method:'POST',body:{accountId:select.value,mode:choice.value()}});dialog.close();dialog.remove();notify(t('Account added. The Agent will apply it automatically.'));await onDone();}catch(error){notify(errorCopy(error));submit.disabled=false;}}},el('h2',{text:t('Add account')}),el('label',{},t('Account Profile'),select),available.length?null:el('div',{class:'notice',text:t('Create another Account Profile before adding a Codex login.')}),choice.field,el('div',{class:'actions'},submit,el('button',{type:'button','data-testid':'new-profile-from-device',text:t('New profile'),onclick:createProfile}),el('button',{type:'button',text:t('Cancel'),onclick:()=>dialog.close()})));dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.isConnected)dialog.remove();});dialog.showModal();select.focus();
}
// Patch display nodes without detaching stable elements, focus, or scroll anchors.
function updateDisplay(current,next){
  if(current.nodeType!==next.nodeType||current.nodeName!==next.nodeName){current.replaceWith(next);return next;}
  if(current.nodeType===3){if(current.nodeValue!==next.nodeValue)current.nodeValue=next.nodeValue;return current;}
  for(const attr of [...current.attributes])if(!next.hasAttribute(attr.name))current.removeAttribute(attr.name);
  for(const attr of [...next.attributes])if(current.getAttribute(attr.name)!==attr.value)current.setAttribute(attr.name,attr.value);
  const before=[...current.childNodes],after=[...next.childNodes];
  for(let index=0;index<Math.max(before.length,after.length);index++){
    if(!after[index])before[index].remove();else if(!before[index])current.append(after[index]);else updateDisplay(before[index],after[index]);
  }
  return current;
}
async function deviceDetail(id){
  if(pollTimer){clearTimeout(pollTimer);pollTimer=null;}
  const root=el('div');shell(root,'devices');
  try{
    let[device,usage,groupsData,accountsData]=await Promise.all([api(`/devices/${encodeURIComponent(id)}`),api(`/usage/devices/${encodeURIComponent(id)}?range=${range}`),api('/groups'),api('/accounts?range=all')]);
    if(!root.isConnected)return;
    const profiles=list(device,'profiles'),groups=list(groupsData,'groups'),accountsList=list(accountsData,'accounts'),activeGroups=groups.filter(group=>!group.archivedAt);
    const group=el('select',{},el('option',{value:'',text:t('Unassigned')}),...activeGroups.map(entry=>el('option',{value:entry.id,text:entry.name})));group.value=device.currentGroupId??'';
    const name=el('input',{value:device.name,required:true});
    const controls=el('form',{class:'form compact-form',onsubmit:async event=>{event.preventDefault();try{await api(`/devices/${encodeURIComponent(id)}`,{method:'PATCH',body:{name:name.value}});notify(t('Device renamed'));deviceDetail(id);}catch(error){notify(errorCopy(error));}}},el('h2',{text:t('Device controls')}),el('label',{},t('Name'),name),el('button',{type:'submit',text:t('Rename')}),el('label',{},t('Group'),group),el('button',{type:'button',text:t('Move device'),onclick:async()=>{try{await api(`/devices/${encodeURIComponent(id)}/move`,{method:'POST',body:{groupId:group.value||null}});notify(t('Device moved'));deviceDetail(id);}catch(error){notify(errorCopy(error));}}}),el('button',{type:'button',text:t(device.disabledAt?'Enable device':'Disable device'),onclick:async()=>{try{await api(`/devices/${encodeURIComponent(id)}/disable`,{method:'POST',body:{disabled:!device.disabledAt}});deviceDetail(id);}catch(error){notify(errorCopy(error));}}}),el('button',{type:'button',text:t('Rotate credential'),onclick:async()=>{if(!confirm(t('The current Agent credential will stop working. Continue?')))return;try{const result=await api(`/devices/${encodeURIComponent(id)}/rotate`,{method:'POST',body:{}});secretDialog(result.deviceSecret);}catch(error){notify(errorCopy(error));}}}),el('button',{class:'danger',type:'button',text:t('Remove device'),'data-testid':'remove-device-detail',onclick:()=>removeDeviceDialog(device,()=>{location.hash='#/devices';})}));
    const add=el('button',{class:'primary',type:'button','data-testid':'add-account',text:t('+ Add account'),onclick:()=>addAccountDialog(device,accountsList,()=>deviceDetail(id))});
    const tracked=el(
      'section',
      {class:'profile-section','aria-labelledby':'tracked-accounts'},
      el('div',{class:'toolbar'},el('div',{},el('h2',{id:'tracked-accounts',text:t('Tracked Codex accounts')}),el('div',{class:'muted',text:t('Only accounts explicitly added here are measured.')})),add),
      el('div',{class:'profile-list'},...(profiles.length?profiles.map(profile=>profileRow(device,profile,()=>deviceDetail(id))):[el('div',{class:'empty',text:t('No Codex accounts are tracked on this device.')})]))
    );
    const subtitle=value=>t('{group} | Last seen {time}',{group:value.currentGroupName??t('Unassigned'),time:when(value.lastSeenAt)});
    const title=heading(device.name,subtitle(device),[status(device.state),rangeTabs(()=>deviceDetail(id))]);
    const applyNotice=el('div',{class:'notice error-notice',text:t('Profile configuration could not be applied. Current tracking continues using the previous configuration.')});
    applyNotice.hidden=device.configurationStatus!=='apply_failed';
    const pollNotice=el('div',{class:'notice',role:'status',hidden:true,text:t('Status updates are temporarily unavailable. Retrying...')});
    let usagePanel=usageDetails(usage),profileSnapshot=JSON.stringify(profiles),usageSnapshot=JSON.stringify(usage);
    root.append(title,applyNotice,pollNotice,tracked,el('div',{class:'detail-grid'},usagePanel,el('section',{class:'card'},controls)),el('section',{class:'card'},adjustmentForm({deviceId:id},()=>deviceDetail(id))));
    const currentRange=range,isCurrent=()=>root.isConnected&&location.hash===`#/devices/${encodeURIComponent(id)}`;
    const schedule=()=>{if(isCurrent())pollTimer=setTimeout(poll,3000);};
    const poll=async()=>{
      if(!isCurrent())return;
      if(document.visibilityState==='hidden'){schedule();return;}
      try{
        const[nextDevice,nextUsage]=await Promise.all([api(`/devices/${encodeURIComponent(id)}`),api(`/usage/devices/${encodeURIComponent(id)}?range=${currentRange}`)]);
        if(!isCurrent())return;
        const nextProfiles=list(nextDevice,'profiles'),nextProfileSnapshot=JSON.stringify(nextProfiles),nextUsageSnapshot=JSON.stringify(nextUsage);
        if(device.name!==nextDevice.name)title.querySelector('h1').textContent=nextDevice.name;
        if(subtitle(device)!==subtitle(nextDevice))title.querySelector('.subtitle').textContent=subtitle(nextDevice);
        if(device.state!==nextDevice.state)updateDisplay(title.querySelector('.status'),status(nextDevice.state));
        applyNotice.hidden=nextDevice.configurationStatus!=='apply_failed';
        if(profileSnapshot!==nextProfileSnapshot){
          const container=tracked.querySelector('.profile-list');
          if(nextProfiles.length){
            const existing=new Map([...container.children].map(row=>[row.getAttribute('data-testid'),row])),keep=new Set();
            for(const profile of nextProfiles){const nextRow=profileRow(device,profile,()=>deviceDetail(id)),key=nextRow.getAttribute('data-testid'),old=existing.get(key);keep.add(key);if(old)updateDisplay(old,nextRow);else container.append(nextRow);}
            for(const[key,row]of existing)if(!keep.has(key))row.remove();
          }else updateDisplay(container,el('div',{class:'profile-list'},el('div',{class:'empty',text:t('No Codex accounts are tracked on this device.')})));
          profileSnapshot=nextProfileSnapshot;
        }
        if(usageSnapshot!==nextUsageSnapshot){usagePanel=updateDisplay(usagePanel,usageDetails(nextUsage));usageSnapshot=nextUsageSnapshot;}
        Object.assign(device,nextDevice);pollNotice.hidden=true;
      }catch{if(isCurrent())pollNotice.hidden=false;}
      schedule();
    };
    schedule();
  }catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));}
}
function secretDialog(secret){const dialog=el('dialog',{},el('h2',{text:t('New credential')}),el('div',{class:'notice',text:t('Shown once. Update the Agent configuration securely.')}),el('div',{class:'code-line'},el('code',{text:secret}),el('button',{text:t('Copy'),onclick:()=>navigator.clipboard.writeText(secret)})),el('button',{text:t('Close'),onclick:()=>dialog.close()}));document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
async function addDevice(preferredAccountId=null,draft=null){
  if(pollTimer)clearTimeout(pollTimer);const root=el('div');shell(root,'devices');
  try{
    const[groupsData,accountsData]=await Promise.all([api('/groups'),api('/accounts?range=all')]),groups=list(groupsData,'groups'),accountsList=list(accountsData,'accounts').filter(account=>!account.archivedAt);
    const name=el('input',{required:true,maxlength:'200','data-testid':'device-name',value:draft?.name??''});
    const group=el('select',{},el('option',{value:'',text:t('Unassigned')}),...groups.filter(entry=>!entry.archivedAt).map(entry=>el('option',{value:entry.id,text:entry.name})));
    const profile=el('select',{required:true,'data-testid':'initial-account'},el('option',{value:'',text:t('Select an Account Profile')}),...accountsList.map(account=>el('option',{value:account.id,text:account.name})));
    group.value=draft?.groupId??'';if(accountsList.some(account=>account.id===preferredAccountId))profile.value=preferredAccountId;
    const choice=environmentChoices({testId:'initial-environment',selectedMode:draft?.mode??null});
    const newProfile=el('button',{type:'button','data-testid':'new-profile-from-onboarding',text:t('New profile'),onclick:()=>accountDialog(null,created=>addDevice(created.id,{name:name.value,groupId:group.value,mode:choice.value()}))});
    const form=el('form',{class:'form onboarding-form','data-testid':'add-device-form',onsubmit:async event=>{event.preventDefault();if(!profile.value)return;const button=form.querySelector('[type="submit"]');button.disabled=true;try{const enrollment=await api('/devices',{method:'POST',body:{name:name.value,groupId:group.value||null,accountId:profile.value,mode:choice.value()}});showEnrollment(root,enrollment);}catch(error){notify(errorCopy(error));button.disabled=false;}}},el('label',{},t('Device name'),name),el('label',{},t('Group'),group),el('label',{},t('Account Profile'),profile),accountsList.length?null:el('div',{class:'notice',text:t('Create an Account Profile before adding a device.')}),newProfile,choice.field,el('button',{class:'primary',type:'submit',disabled:accountsList.length===0,text:t('Create device')}));
    root.append(heading(t('Add device'),t('Choose the Codex account to track')),el('section',{class:'card onboarding-card'},form));
  }catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));}
}
function installerCommands(enrollment){
  if(!enrollment||typeof enrollment.enrollmentToken!=='string'||!/^[A-Za-z0-9_-]{20,200}$/.test(enrollment.enrollmentToken)||typeof enrollment.enrollmentId!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(enrollment.enrollmentId))throw new DisplayError(t('Unexpected Server response.'));
  const parsed=new URL(location.origin),local=parsed.hostname==='127.0.0.1'||parsed.hostname==='localhost'||parsed.hostname==='::1';if(parsed.protocol!=='https:'&&!(parsed.protocol==='http:'&&local))throw new DisplayError(t('HTTPS is required for Agent installation.'));const base=parsed.origin,token=enrollment.enrollmentToken,ps=value=>`'${value.replaceAll("'","''")}'`,sh=value=>`'${value.replaceAll("'","'\"'\"'")}'`;
  return[['Windows PowerShell',`& ([scriptblock]::Create((irm ${ps(`${base}/install.ps1`)}))) -ServerUrl ${ps(base)} -EnrollmentToken ${ps(token)}`],['Linux x64',`curl -fsSL ${sh(`${base}/install.sh`)} | sh -s -- --server ${sh(base)} --token ${sh(token)}`],['macOS arm64',`curl -fsSL ${sh(`${base}/install.sh`)} | sh -s -- --server ${sh(base)} --token ${sh(token)}`]];
}
function showEnrollment(root,enrollment){
  let commands;try{commands=installerCommands(enrollment);}catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));return;}
  const state=el('div',{class:'notice','data-testid':'enrollment-state',text:t('Waiting for the Agent to connect...')}),card=el('section',{class:'card enrollment-card'},el('h2',{text:t('Install and connect')}),el('p',{class:'muted',text:t('Enrollment expires {time}. The one-time token is shown only here.',{time:when(enrollment.expiresAt)})}),...commands.map(([platform,command])=>el('div',{class:'install-command'},el('strong',{text:platform}),el('div',{class:'code-line'},el('code',{text:command,'data-testid':`command-${platform.split(' ')[0].toLowerCase()}`}),el('button',{type:'button',text:t('Copy'),onclick:()=>navigator.clipboard?.writeText(command)})))),state);
  root.replaceChildren(heading(t('Add device'),t('Run one command on the device')),card);
  let shownStatus=null;
  const poll=async()=>{
    if(!root.isConnected)return;
    try{
      const result=await api(`/device-enrollments/${encodeURIComponent(enrollment.enrollmentId)}`);
      if(!root.isConnected)return;
      if(['registered','connected'].includes(result.status)&&typeof result.deviceId==='string'){
        if(shownStatus!==result.status){
          state.className=result.status==='connected'?'notice success-notice':'notice';
          state.replaceChildren(t(result.status==='connected'?'Agent connected.':'Registered. Waiting for the first Agent status report...'),el('a',{class:'button primary',href:`#/devices/${encodeURIComponent(result.deviceId)}`,text:t('View device')}));
        }
        shownStatus=result.status;if(result.status==='connected')return;
      }else if(result.status==='expired'){state.textContent=t('Enrollment expired. Create a new device enrollment.');return;}
      else if(result.status!=='pending')throw new DisplayError(t('Unexpected Server response.'));
    }catch(error){if(root.isConnected){state.textContent=t('Connection check failed: {error}',{error:errorCopy(error)});shownStatus=null;}}
    if(root.isConnected)pollTimer=setTimeout(poll,2000);
  };poll();
}
async function accounts(){
  const root=el('div');
  const add=el('button',{class:'primary',type:'button','data-testid':'new-profile',text:t('New profile'),onclick:()=>accountDialog(null,accounts)});
  root.append(heading(t('Accounts'),t('Account Profiles and tracking coverage'),[rangeTabs(accounts),add]));shell(root,'accounts');
  try{
    const data=await api(`/accounts?range=${range}`),accountRows=list(data,'accounts'),activeAccounts=accountRows.filter(account=>!account.archivedAt);
    const rows=activeAccounts.length?activeAccounts.map(account=>el('div',{class:'list-row','data-testid':`account-${account.id}`},
      el('div',{},el('a',{href:`#/accounts/${encodeURIComponent(account.id)}`,text:account.name}),el('div',{class:'muted',text:`${coverageCopy(account.trackingCoverage)}${account.reference?` | ${t('Reference profile')}`:''}`})),
      el('div',{class:'right'},status(account.quota.status),el('div',{class:'muted',text:t('{tokens} measured tokens',{tokens:fmt(account.measured.totalTokens)})}),el('button',{class:'danger',type:'button',text:t('Delete'),'data-testid':`delete-account-${account.id}`,onclick:()=>deleteAccountDialog(account,accounts)}))
    )):[el('div',{class:'empty',text:t('No Account Profiles yet.')})];
    root.append(el('div',{class:'list'},...rows));
  }catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}
}
function accountDialog(account,onDone,onCancel=null){
  const dialog=el('dialog',{'data-testid':'account-profile-dialog'}),name=el('input',{required:true,maxlength:'200',value:account?.name??'','data-testid':'profile-name'}),reference=el('input',{type:'checkbox'});let saved=false,saving=false;reference.checked=account?.reference??false;
  const save=el('button',{class:'primary',type:'submit','data-testid':'save-profile',text:t('Save')}),cancel=el('button',{type:'button','data-testid':'cancel-profile',text:t('Cancel'),onclick:()=>dialog.close()});
  const form=el('form',{class:'form',onsubmit:async event=>{event.preventDefault();if(saving)return;saving=true;save.disabled=true;cancel.disabled=true;try{const result=await api(account?`/accounts/${encodeURIComponent(account.id)}`:'/accounts',{method:account?'PATCH':'POST',body:{name:name.value,reference:reference.checked}});saved=true;dialog.close();dialog.remove();await onDone(result);}catch(error){notify(errorCopy(error));saving=false;save.disabled=false;cancel.disabled=false;}}},el('h2',{text:t(account?'Edit Account Profile':'Create Account Profile')}),el('p',{class:'muted',text:t('This is a Meter label, not a verified provider identity.')}),el('label',{},t('Profile name'),name),el('label',{class:'check-label'},reference,` ${t('Reference profile')}`),el('div',{class:'actions'},save,cancel));dialog.append(form);document.body.append(dialog);dialog.addEventListener('cancel',event=>{if(saving)event.preventDefault();});dialog.addEventListener('close',()=>{if(dialog.isConnected)dialog.remove();if(!saved&&!saving)onCancel?.();},{once:true});dialog.showModal();name.focus();
}
async function accountDetail(id){
  const root=el('div');shell(root,'accounts');
  try{
    const[account,attribution]=await Promise.all([api(`/accounts/${encodeURIComponent(id)}?range=${range}`),api(`/accounts/${encodeURIComponent(id)}/quota-attribution`)]),devicesList=list(account,'devices'),groupList=list(account,'groups');
    const edit=el('button',{type:'button',text:t('Edit'),onclick:()=>accountDialog(account,()=>accountDetail(id))}),remove=el('button',{class:'danger',type:'button',text:t('Delete profile'),'data-testid':'delete-account-detail',onclick:()=>deleteAccountDialog(account,()=>{location.hash='#/accounts';})}),coverage=account.trackingCoverage;
    const coveragePanel=el('section',{class:'coverage-band'},el('div',{},el('div',{class:'metric-label',text:t('Tracking coverage')}),el('div',{class:'big compact',text:coverageCopy(coverage)})),coverage?.status==='full'?status('tracking'):status(coverage?.status==='unknown'?'waiting_for_agent':'quota_unavailable'));
    const deviceRows=devicesList.length?devicesList.map(device=>el('div',{class:'list-row'},el('div',{},el('a',{href:`#/devices/${encodeURIComponent(device.deviceId)}`,text:device.name}),el('div',{class:'muted',text:t('{mode} | Last activity: {time}',{mode:environmentLabel(device.mode),time:when(device.lastActivityAt)})})),el('div',{class:'right'},status(device.trackingState),el('strong',{text:t('{tokens} tokens',{tokens:fmt(device.measured.totalTokens)})})))):[el('div',{class:'empty',text:t('No registered devices.')})];
    root.append(heading(account.name,t('Measured usage and registered Device coverage'),[rangeTabs(()=>accountDetail(id)),edit,remove]),coveragePanel,usageDetails({measured:account.measured,adjusted:{totalTokens:'0'},combined:{totalTokens:account.measured.totalTokens}}),cycleView({accounts:[account]},attribution),el('section',{class:'card'},el('h2',{text:t('Tracked devices')}),...deviceRows),el('section',{class:'card'},el('h2',{text:t('Group breakdown')}),...groupList.map(group=>el('div',{class:'list-row'},el('span',{text:group.name}),el('strong',{text:fmt(group.measured.totalTokens)}))),el('div',{class:'list-row'},el('span',{text:t('Unassigned')}),el('strong',{text:fmt(account.unassigned.totalTokens)}))));
  }catch(error){root.append(el('p',{class:'error',text:errorCopy(error)}));}
}
async function settings(){const root=el('div');shell(root,'settings');try{const[data,devicesData]=await Promise.all([api('/settings'),api('/devices')]);const timezone=el('input',{value:data.timezone??'UTC',required:true}),reporter=el('select',{},el('option',{value:'',text:t('None')}),...devicesData.devices.filter(d=>!d.disabledAt).map(d=>el('option',{value:d.id,text:d.name}))),online=el('input',{type:'number',min:'10',required:true,value:data.onlineThresholdSeconds}),stale=el('input',{type:'number',min:'11',max:'86400',required:true,value:data.staleThresholdSeconds});reporter.value=data.quotaReporterDeviceId??'';const form=el('form',{class:'form',onsubmit:async e=>{e.preventDefault();try{await api('/settings',{method:'PATCH',body:{timezone:timezone.value,quotaReporterDeviceId:reporter.value||null,onlineThresholdSeconds:Number(online.value),staleThresholdSeconds:Number(stale.value)}});notify(t('Settings saved'));settings();}catch(err){notify(errorCopy(err));}}},el('label',{},t('Aggregation timezone'),timezone),el('label',{},t('Quota reporter device'),reporter),el('div',{class:'form-row'},el('label',{},t('Online threshold (seconds)'),online),el('label',{},t('Offline threshold (seconds)'),stale)),el('p',{class:'muted',text:t('A device is Online below the first threshold, Stale between thresholds, and Offline above the second.')}),el('button',{class:'primary',type:'submit',text:t('Save settings')}));root.append(heading(t('Settings'),t('Timezone, quota reporter, and centralized device-state thresholds')),el('section',{class:'card'},form));}catch(e){root.append(el('p',{class:'error',text:errorCopy(e)}));}}
async function route(){if(pollTimer){clearTimeout(pollTimer);pollTimer=null;}if(!csrf){try{const session=await api('/auth/session');csrf=session.csrfToken;}catch{return;}}const parts=(location.hash.replace(/^#\/?/,'')||'overview').split('/').map(decodeURIComponent);if(parts[0]==='overview')return overview();if(parts[0]==='groups'&&parts[1])return groupDetail(parts[1]);if(parts[0]==='groups')return groups();if(parts[0]==='devices'&&parts[1]==='add')return addDevice();if(parts[0]==='devices'&&parts[1])return deviceDetail(parts[1]);if(parts[0]==='devices')return devices();if(parts[0]==='accounts'&&parts[1])return accountDetail(parts[1]);if(parts[0]==='accounts')return accounts();if(parts[0]==='settings')return settings();location.hash='#/overview';}
applyDocumentLanguage();window.addEventListener('hashchange',route);route();
